local _, addonTable = ...

-- Camelot's Game Menu and Settings pages are not part of ClassicUA's legacy
-- GlobalStrings subset. Keep these as display-only translations: the actual
-- Blizzard globals must remain English because Camelot uses some as data keys.
local settings = {
    -- Game menu and Settings navigation
    ["Game Menu"] = "Меню гри",
    ["Return to Game"] = "Повернутися до гри",
    ["Settings"] = "Налаштування",
    ["Options"] = "Налаштування",
    ["Edit Mode"] = "Режим редагування",
    ["Macros"] = "Макроси",
    ["AddOns"] = "Аддони",
    ["Support"] = "Підтримка",
    ["Log Out"] = "Вийти з обл. запису",
    ["Exit Game"] = "Вийти з гри",
    ["Issue Reporter"] = "Звітувати про проблему",
    ["Search Settings"] = "Пошук налаштувань",
    ["Search"] = "Пошук",
    ["System"] = "Система",
    ["Gameplay"] = "Ігровий процес",
    ["Accessibility"] = "Доступність",
    ["General"] = "Загальні",
    ["Graphics"] = "Графіка",
    ["Advanced"] = "Розширені",
    ["Advanced Options"] = "Розширені налаштування",
    ["Network"] = "Мережа",
    ["Sound"] = "Звук",
    ["Voice Chat"] = "Голосовий чат",
    ["Controls"] = "Керування",
    ["Combat"] = "Бій",
    ["Action Bars"] = "Панелі дій",
    ["Names"] = "Імена",
    ["Interface"] = "Інтерфейс",
    ["Raid Frames"] = "Рейдові рамки",
    ["Social"] = "Спілкування",
    ["Tutorials"] = "Навчання",
    ["Keybindings"] = "Призначення клавіш",
    ["Key Bindings"] = "Призначення клавіш",
    ["Mouse"] = "Миша",
    ["Camera"] = "Камера",
    ["Languages"] = "Мови",
    ["Languages and Social"] = "Мови та спілкування",
    ["Audio"] = "Аудіо",
    ["Audio Assist"] = "Допомога зі звуком",
    ["Colors"] = "Кольори",
    ["Gamepad (Alpha)"] = "Геймпад (альфа)",
    ["Nameplates"] = "Індикатори імен",
    ["Ping System"] = "Система сигналів",
    ["Subtitles"] = "Субтитри",
    ["Features"] = "Функції",
    ["Colorblind Mode"] = "Режим корекції кольорів",
    ["Text to Speech"] = "Перетворення тексту на мовлення",
    ["Speech to Text"] = "Перетворення мовлення на текст",

    -- Common controls
    ["Apply"] = "Застосувати",
    ["Okay"] = "Гаразд",
    ["OK"] = "Гаразд",
    ["Cancel"] = "Скасувати",
    ["Close"] = "Закрити",
    ["Defaults"] = "Типові налаштування",
    ["Default"] = "Типове",
    ["Reset"] = "Скинути",
    ["Reset to Default"] = "Скинути до типових",
    ["Enable"] = "Увімкнути",
    ["Disable"] = "Вимкнути",
    ["Enabled"] = "Увімкнено",
    ["Disabled"] = "Вимкнено",
    ["None"] = "Немає",
    ["Not Bound"] = "Не призначено",
    ["SHIFT key"] = "клавіша SHIFT",
    ["Low"] = "Низька",
    ["Fair"] = "Задовільна",
    ["Good"] = "Добра",
    ["High"] = "Висока",
    ["Ultra"] = "Ультра",

    -- Graphics and display
    ["Display"] = "Відображення",
    ["Display Mode"] = "Режим відображення",
    ["Windowed"] = "Віконний",
    ["Windowed (Fullscreen)"] = "Віконний (на весь екран)",
    ["Fullscreen"] = "Повноекранний",
    ["Resolution"] = "Роздільна здатність",
    ["Render Scale"] = "Масштаб рендерингу",
    ["Vertical Sync"] = "Вертикальна синхронізація",
    ["Anti-Aliasing"] = "Згладжування",
    ["Multisample Anti-Aliasing"] = "Багатовибіркове згладжування",
    ["Texture Resolution"] = "Роздільна здатність текстур",
    ["Color 2x / Depth 2x"] = "Колір 2× / глибина 2×",
    ["Texture Filtering"] = "Фільтрація текстур",
    ["Projected Textures"] = "Проєкційні текстури",
    ["View Distance"] = "Дальність огляду",
    ["Environment Detail"] = "Деталізація довкілля",
    ["Ground Clutter"] = "Густота рослинності",
    ["Shadow Quality"] = "Якість тіней",
    ["Liquid Detail"] = "Деталізація рідин",
    ["Particle Density"] = "Щільність частинок",
    ["Depth Effects"] = "Ефекти глибини",
    ["Compute Effects"] = "Обчислювальні ефекти",
    ["Outline Mode"] = "Режим контурів",
    ["Graphics Quality"] = "Якість графіки",
    ["Base Settings"] = "Базові налаштування",
    ["Raid and Battleground"] = "Рейди та поля бою",
    ["Max Foreground FPS"] = "Максимальна частота кадрів на передньому плані",
    ["Max Background FPS"] = "Максимальна фонова частота кадрів",
    ["Target FPS"] = "Цільова частота кадрів",
    ["Resample Quality"] = "Якість масштабування",
    ["Graphics API"] = "Графічний API",
    ["Graphics Card"] = "Відеокарта",
    ["Monitor"] = "Монітор",
    ["Gamma"] = "Гама",
    ["Brightness"] = "Яскравість",
    ["Contrast"] = "Контраст",

    -- Audio
    ["Enable Sound"] = "Увімкнути звук",
    ["Master Volume"] = "Загальна гучність",
    ["Sound Effects"] = "Звукові ефекти",
    ["Music"] = "Музика",
    ["Ambience"] = "Звуки оточення",
    ["Dialog"] = "Діалоги",
    ["Sound in Background"] = "Звук у фоновому режимі",
    ["Error Speech"] = "Озвучення помилок",

    -- Controls, combat, and action bars
    ["Auto Loot"] = "Автоматичний збір здобичі",
    ["Sticky Targeting"] = "Утримання вибраної цілі",
    ["Click-to-Move"] = "Переміщення клацанням",
    ["Mouse Sensitivity"] = "Чутливість миші",
    ["Invert Mouse"] = "Інвертувати мишу",
    ["Enable Mouseover Cast"] = "Застосування заклять наведенням",
    ["Auto Dismount in Flight"] = "Автоматично спішуватися в польоті",
    ["Enable Interact Key"] = "Увімкнути клавішу взаємодії",
    ["Interact Key"] = "Клавіша взаємодії",
    ["Floating Combat Text"] = "Плавучий бойовий текст",
    ["Attack on Assist"] = "Атакувати під час допомоги",
    ["Stop Auto Attack"] = "Зупиняти автоатаку",
    ["Target of Target"] = "Ціль цілі",
    ["Loss of Control Alerts"] = "Сповіщення про втрату контролю",
    ["Spell Alert Opacity"] = "Прозорість сповіщень про закляття",
    ["Lock Action Bars"] = "Заблокувати панелі дій",
    ["Always Show Action Bars"] = "Завжди показувати панелі дій",
    ["Show Numbers for Cooldowns"] = "Показувати числа часу відновлення",
    ["Bottom Left Bar"] = "Нижня ліва панель",
    ["Bottom Right Bar"] = "Нижня права панель",
    ["Right Bar"] = "Права панель",
    ["Right Bar 2"] = "Права панель 2",

    -- Names and interface
    ["My Name"] = "Моє ім'я",
    ["Friendly Players"] = "Дружні гравці",
    ["Enemy Players"] = "Ворожі гравці",
    ["Friendly Units"] = "Дружні істоти",
    ["Enemy Units"] = "Ворожі істоти",
    ["Minions"] = "Прислужники",
    ["Totems"] = "Тотеми",
    ["Unit Nameplates"] = "Індикатори істот",
    ["Friendly NPC Nameplates"] = "Індикатори імен дружніх NPC",
    ["Only Show Names"] = "Показувати лише імена",
    ["Realm Name"] = "Назва світу",
    ["Show Offscreen Nameplates"] = "Показувати індикатори імен поза екраном",
    ["Stack Nameplates"] = "Складати індикатори імен",
    ["Use Class Color for Names"] = "Використовувати колір класу для імен",
    ["Larger Nameplates"] = "Збільшені індикатори",
    ["Personal Resource Display"] = "Особистий індикатор ресурсів",
    ["Status Text"] = "Текст стану",
    ["Display Lua Errors"] = "Показувати помилки Lua",
    ["Show Tutorials"] = "Показувати навчальні підказки",
    ["Reset Tutorials"] = "Скинути навчання",
    ["Chat Bubbles"] = "Бульбашки чату",
    ["Party Chat Bubbles"] = "Бульбашки групового чату",
    ["Raid Chat Bubbles"] = "Бульбашки рейдового чату",
    ["Replace Player Frame Portraits"] = "Замінити портрети рамок гравців",
    ["Replace My Frame Portrait"] = "Замінити портрет моєї рамки",
    ["Show Low-Level Quests"] = "Показувати низькорівневі завдання",
    ["Toasts"] = "Сповіщення",
    ["Show Item Toasts"] = "Показувати сповіщення про предмети",
    ["Show Collection Toasts"] = "Показувати сповіщення про колекції",
    ["Show Recipe Toasts"] = "Показувати сповіщення про рецепти",
    ["Open Loot Window at Mouse"] = "Відкривати вікно здобичі біля курсора",
    ["Mouse Look Speed"] = "Швидкість огляду мишею",
    ["Auto Loot Key"] = "Клавіша автоматичного збору",
    ["Lock Cursor to Window"] = "Обмежити курсор вікном",
    ["Combine Bags"] = "Об'єднати сумки",
    ["Interact On Left Click"] = "Взаємодія лівою кнопкою миші",
    ["Auto Cancel Away Mode"] = "Автоматично скасовувати стан «Відійшов»",
    ["Interact With Target"] = "Взаємодія з ціллю",
    ["Interact Key Sound Cue"] = "Звуковий сигнал клавіші взаємодії",
    ["Enable Mouse Sensitivity"] = "Увімкнути чутливість миші",
}

addonTable.forever_ui = addonTable.forever_ui or {}
for english, ukrainian in pairs(settings) do
    if addonTable.forever_ui[english] == nil then
        addonTable.forever_ui[english] = ukrainian
    end
end

-- Same English label can mean different things in different parts of the UI.
addonTable.forever_ui_context = {
    { text = "Back", frame = "Quest", translation = "Назад" },
    { text = "Common", frame = "LootFrame", translation = "Звичайний" },
    { text = "Common", frame = "LootButton", translation = "Звичайний" },
    { text = "General", frame = "ChatFrame", translation = "Загальний" },
    { text = "General", frame = "CharacterStatsPane", translation = "Загальне" },
    { text = "General", frame = "Settings", translation = "Загальні" },
    { text = "invites you to join the guild:", frame = "GuildInviteFrameInviteText", translation = "запрошує вас до гільдії:" },
    { text = "Join Guild", frame = "GuildInviteFrameJoinButton", translation = "Вступити" },
    { text = "Decline Invitation", frame = "GuildInviteFrameDeclineButton", translation = "Відхилити" },
}
