-- English source templates and user-reviewed Ukrainian gossip translations.
-- Exported by automation/export_gossip_hashed.py; source worklists: automation/gosips2.
-- Source licensing: classic-db/LICENSE.md and classic-db/COPYRIGHT.md.
local _, addonTable = ...
addonTable.gossip_hashed = addonTable.gossip_hashed or { version = 1, rows = {} }
local rows = {
    [1361490393] = {
        ["english"] = { [1] = "Good day to you, citizen. Have you come to aid us against the Scourge?" },
        ["text"] = "Добридень, громадянине. Ти прийшов допомогти нам проти Скари?",
        ["npcs"] = { [1] = 16478, [2] = 16494 },
        ["roles"] = { ["greeting"] = true },
    },
    [4001441390] = {
        ["english"] = { [1] = "For Gnomeregan!" },
        ["text"] = "За Ґномреґан!",
        ["npcs"] = { [1] = 6579 },
        ["roles"] = { ["greeting"] = true },
    },
    [1249635156] = {
        ["english"] = { [1] = "Greetings, $c.  If you're a friend of Colonel Kurzen then I'll have you cut down where you stand! but if you've come to aid us, then lend an ear..." },
        ["text"] = "Вітаю, $c. Якщо ти друг полковника Курцена, я накажу стяти тебе на місці! Але якщо ти прийшов нам допомогти — слухай...",
        ["npcs"] = { [1] = 469 },
        ["roles"] = { ["greeting"] = true },
    },
    [2844574987] = {
        ["english"] = { [1] = "Good day, $glad:lass;! Perhaps you could help me with some things that need to be taken care of." },
        ["text"] = "Добридень, $gхлопче:дівчино;! Можливо, допоможеш мені з кількома справами, які треба владнати.",
        ["npcs"] = { [1] = 3663 },
        ["roles"] = { ["greeting"] = true },
    },
    [1370871083] = {
        ["english"] = { [1] = "There is no treat finer than Barbecued Buzzard Wing." },
        ["text"] = "Немає кращих ласощів за крило канюка на грилі.",
        ["npcs"] = { [1] = 2818 },
        ["roles"] = { ["greeting"] = true },
    },
    [522006174] = {
        ["english"] = { [1] = "Hello, citizen.  You look like a $g man : woman; with a purpose - do you have business with the Stormwind Army?" },
        ["text"] = "Привіт, $gгромадянине:громадянко;. Схоже, ти $gчоловік:жінка; із метою — маєш справи з армією Штормовію?",
        ["npcs"] = { [1] = 261 },
        ["roles"] = { ["greeting"] = true },
    },
    [4015252705] = {
        ["english"] = { [1] = "Nethergarde keep always needs more supplies - supplies to help our mages in their research, and supplies to keep our defenders in top fighting shape." },
        ["text"] = "Твердині Підсіття завжди потрібно більше припасів — припасів для досліджень наших магів і припасів, щоб наші захисники лишалися в найкращій бойовій формі.",
        ["npcs"] = { [1] = 5393 },
        ["roles"] = { ["greeting"] = true },
    },
    [2264017511] = {
        ["english"] = { [1] = "I never feel warm anymore..." },
        ["text"] = "Мені вже ніколи не буває тепло...",
        ["npcs"] = { [1] = 10926 },
        ["roles"] = { ["greeting"] = true },
    },
    [3283312182] = {
        ["english"] = { [1] = "The spirit of Stonetalon weeps... It weeps from its mountain peaks, to its rivers, to its severed, dying trees." },
        ["text"] = "Дух Каміннопазуристих гір плаче... Плаче з гірських вершин, у річках і в зрубаних, помираючих деревах.",
        ["npcs"] = { [1] = 4049 },
        ["roles"] = { ["greeting"] = true },
    },
    [3177070768] = {
        ["english"] = { [1] = "Desolace is not such a bad place, if you don't mind the constant harassments from the centaurs." },
        ["text"] = "Спустошище — не таке вже й погане місце, якщо тебе не дратують постійні напади кентаврів.",
        ["npcs"] = { [1] = 11259 },
        ["roles"] = { ["greeting"] = true },
    },
    [416641964] = {
        ["english"] = { [1] = "You'll not find a greater cache of knowledge than in the Royal Library of Stormwind!" },
        ["text"] = "Ніде не знайдеш більшої скарбниці знань, ніж у Королівській бібліотеці Штормовію!",
        ["npcs"] = { [1] = 1440 },
        ["roles"] = { ["greeting"] = true },
    },
    [3987271560] = {
        ["english"] = { [1] = "Who is this $c who goes before the Court of Lakshire in the Kingdom of Stormwind?  State your business within this township, $R.  The orc threat to the Kingdom is far too great to squander time in idle conversation." },
        ["text"] = "Хто цей $c, що постає перед судом Приозер'я в королівстві Штормовій? Виклади свою справу в цьому місті, $R. Орча загроза королівству надто велика, щоб марнувати час на пусті балачки.",
        ["npcs"] = { [1] = 344 },
        ["roles"] = { ["greeting"] = true },
    },
    [1591496837] = {
        ["english"] = { [1] = "Driving a Steam Tank isn't for everyone.  It takes an iron grip and nerves of steel...lucky I have both!  How about you?  How's your mettle?  Want to prove it to me?" },
        ["text"] = "Керувати паровим танком дано не кожному. Тут потрібні залізна хватка й сталеві нерви... на щастя, у мене є і те, і те! А як щодо тебе? Наскільки ти міцний? Хочеш довести це мені?",
        ["npcs"] = { [1] = 1377 },
        ["roles"] = { ["greeting"] = true },
    },
    [2944076763] = {
        ["english"] = { [1] = "You must be hard up to be wandering this Badlands, $c. A hard up like me.$B$BOr maybe you're here because you're crazy. Crazy, like me." },
        ["text"] = "Тобі, мабуть, геть скрутно, раз ти блукаєш Безплідними краями, $c. Так само скрутно, як і мені.$B$BА може, ти тут, бо божевільний. Божевільний, як я.",
        ["npcs"] = { [1] = 2817 },
        ["roles"] = { ["greeting"] = true },
    },
    [911909344] = {
        ["english"] = { [1] = "Sometimes I think there's a big gray cloud in the sky, just raining down bad luck upon us. First, we're driven off our land, and now we can't even get out of Westfall. Everything's a mess. Something needs to be done." },
        ["text"] = "Іноді мені здається, ніби в небі висить велика сіра хмара й без упину сипле на нас невдачі. Спершу нас прогнали з нашої землі, а тепер ми навіть не можемо вибратися із Західного краю. Усе шкереберть. Треба щось робити.",
        ["npcs"] = { [1] = 238 },
        ["roles"] = { ["greeting"] = true },
    },
    [68106695] = {
        ["english"] = { [1] = "Hello, friend. What can I do for you?" },
        ["text"] = "Привіт, друже. Чим можу допомогти?",
        ["npcs"] = { [1] = 4078 },
        ["roles"] = { ["greeting"] = true },
    },
    [711445941] = {
        ["english"] = { [1] = "Enchanting is the art of improving existing items through magic. " },
        ["text"] = "Зачарування — це мистецтво магічного поліпшення вже наявних предметів. ",
        ["npcs"] = { [1] = 1317, [2] = 3011, [3] = 3345, [4] = 3606, [5] = 4213, [6] = 4616, [7] = 5038, [8] = 5157, [9] = 5695, [10] = 7949, [11] = 11065, [12] = 11066, [13] = 11067, [14] = 11068, [15] = 11070, [16] = 11071, [17] = 11072, [18] = 11073, [19] = 11074 },
        ["roles"] = { ["greeting"] = true },
    },
    [4113775538] = {
        ["english"] = { [1] = "Our only hope is to create something good from an already bad situation." },
        ["text"] = "Наша єдина надія — створити щось добре з уже поганої ситуації.",
        ["npcs"] = { [1] = 5767 },
        ["roles"] = { ["greeting"] = true },
    },
    [3668644224] = {
        ["english"] = { [1] = "A warrior's path is one of determination, $gbrother:sister;.  It may begin with strength of arms, but it endures through force of will." },
        ["text"] = "Шлях воїна — це шлях рішучості, $gбрате:сестро;. Він може починатися з сили рук, та тримається на силі волі.",
        ["npcs"] = { [1] = 4088 },
        ["roles"] = { ["greeting"] = true },
    },
    [3507797366] = {
        ["english"] = { [1] = "What business brings you before the Court of Lakeshire and the Honorable Magistrate Solomon?" },
        ["text"] = "Яка справа привела тебе перед суд Приозер'я та шановного магістрата Соломона?",
        ["npcs"] = { [1] = 900 },
        ["roles"] = { ["greeting"] = true },
    },
    [410384532] = {
        ["english"] = { [1] = "The dust of the Barrens parches my throat more and more every day, $N. But it is worth the sacrifice to remain here if it helps the Horde and the warchief." },
        ["text"] = "Пил Степів дедалі сильніше сушить мені горло, $N. Та ця жертва варта того, якщо моє перебування тут допомагає Орді та Вождю.",
        ["npcs"] = { [1] = 3428 },
        ["roles"] = { ["greeting"] = true },
    },
    [783372778] = {
        ["english"] = { [1] = "Welcome!" },
        ["text"] = "Ласкаво просимо!",
        ["npcs"] = { [1] = 2485, [2] = 2489, [3] = 2492, [4] = 4165, [5] = 5957, [6] = 5958 },
        ["roles"] = { ["greeting"] = true },
    },
    [651372795] = {
        ["english"] = { [1] = "Adventure from lands far and near $bMeeting with folks both odd and queer $bBut if of me a question you ask $bYou must first complete a simple task!" },
        ["text"] = "Пригоди з земель близьких й далеких $bЗустрічі з дивними людьми й химерними $bТа як мене про щось спитаєш ти $bСпершу просте завдання виконай!",
        ["npcs"] = { [1] = 239 },
        ["roles"] = { ["greeting"] = true },
    },
    [3223388223] = {
        ["english"] = { [1] = "Be careful where you put that foot of yours, $gmister:ma'am;.  We're not all blessed with the lofty height of a $r." },
        ["text"] = "Дивись, куди ставиш ту свою ногу, $gпане:пані;. Не всім пощастило мати такий величний зріст, як у $r.",
        ["npcs"] = { [1] = 4453 },
        ["roles"] = { ["greeting"] = true },
    },
    [2837776461] = {
        ["english"] = { [1] = "Hello, druid!  Ready for some training?" },
        ["text"] = "Привіт, друїде! Готовий до тренування?",
        ["npcs"] = { [1] = 3033, [2] = 3034, [3] = 3036, [4] = 3060, [5] = 3064, [6] = 3597, [7] = 3602, [8] = 4217, [9] = 4218, [10] = 4219, [11] = 5504, [12] = 5505, [13] = 5506, [14] = 8142, [15] = 9465, [16] = 12042 },
        ["roles"] = { ["greeting"] = true },
    },
    [3839126782] = {
        ["english"] = { [1] = "We cannot take care of all the threats in this area alone. We could use another fighting hand, $n." },
        ["text"] = "Ми не здатні самотужки впоратися з усіма загрозами в цій місцевості. Нам не завадить ще одна бойова рука, $n.",
        ["npcs"] = { [1] = 10537 },
        ["roles"] = { ["greeting"] = true },
    },
    [3044367263] = {
        ["english"] = { [1] = "When I was first offered the title of Southshore Magistrate I was exalted to have earned such a commission so early in my career.$B$BBut now that I'm here, I wonder if I'd have been better off shuffling papers in Stormwind." },
        ["text"] = "Коли мені вперше запропонували титул магістрата Південнобережжя, я був у захваті, що так рано в кар'єрі заслужив таке призначення.$B$BА тепер, коли я тут, думаю, чи не краще було б перекладати папери у Штормовії.",
        ["npcs"] = { [1] = 2276 },
        ["roles"] = { ["greeting"] = true },
    },
    [1881285744] = {
        ["english"] = { [1] = "Another fine day in the jungle!  It's going to be quite a hunt, I can feel it.  Once Barnil is done cleaning the guns, I'm taking the hunting party deep into the twisting vines.  Not such a bad way for an old war vet to spend his retirement, eh?" },
        ["text"] = "Ще один чудовий день у джунглях! Відчуваю, полювання буде славне. Щойно Барніл закінчить чистити рушниці, я поведу мисливську ватагу глибоко в переплетення ліан. Непоганий спосіб для старого ветерана провести пенсію, еге ж?",
        ["npcs"] = { [1] = 715 },
        ["roles"] = { ["greeting"] = true },
    },
    [1367233285] = {
        ["english"] = { [1] = "I never miss..." },
        ["text"] = "Я ніколи не промахуюся...",
        ["npcs"] = { [1] = 9081 },
        ["roles"] = { ["greeting"] = true },
    },
    [1550899332] = {
        ["english"] = { [1] = "Researching in Theramore is an interesting job, but it's sure hard to find a soft bed in this town!" },
        ["text"] = "Досліджувати в Тераморі цікаво, але знайти в цьому місті м'яке ліжко — справжнє випробування!",
        ["npcs"] = { [1] = 4794 },
        ["roles"] = { ["greeting"] = true },
    },
    [3348790093] = {
        ["english"] = { [1] = "We're here to make a profit.  And having our goods stolen is no way to make a profit." },
        ["text"] = "Ми тут заради прибутку. А коли наші товари крадуть — прибутку не буде.",
        ["npcs"] = { [1] = 7882 },
        ["roles"] = { ["greeting"] = true },
    },
    [3142690936] = {
        ["english"] = { [1] = "Hello, priest!  Ready for some training?" },
        ["text"] = "Привіт, жерцю! Готовий до тренування?",
        ["npcs"] = { [1] = 375, [2] = 376, [3] = 377, [4] = 837, [5] = 1226, [6] = 2123, [7] = 2129, [8] = 3044, [9] = 3045, [10] = 3046, [11] = 3595, [12] = 3600, [13] = 3706, [14] = 3707, [15] = 4090, [16] = 4091, [17] = 4092, [18] = 4606, [19] = 4607, [20] = 4608, [21] = 5141, [22] = 5142, [23] = 5143, [24] = 5484, [25] = 5489, [26] = 5994, [27] = 6014, [28] = 6018, [29] = 11397, [30] = 11401, [31] = 11406 },
        ["roles"] = { ["greeting"] = true },
    },
    [3276688082] = {
        ["english"] = { [1] = "I'm in the middle of a very important task.  Prospector business.  Unless you have something equally important to say, which I doubt, then you'll have to excuse me." },
        ["text"] = "Я посеред дуже важливої справи. Справи старателя. Якщо тобі нема чого сказати настільки ж важливого, у чому я сумніваюся, доведеться мене вибачити.",
        ["npcs"] = { [1] = 1356 },
        ["roles"] = { ["greeting"] = true },
    },
    [1598317865] = {
        ["english"] = { [1] = "The creation of Teldrassil was a grand achievement, but now the world must shift to regain its balance." },
        ["text"] = "Створення Тельдрассіля було великим звершенням, але тепер світ мусить змінитися, щоб відновити рівновагу.",
        ["npcs"] = { [1] = 2080 },
        ["roles"] = { ["greeting"] = true },
    },
    [2673096456] = {
        ["english"] = { [1] = "Greetings!  Can I teach you how to turn beast hides into armor?", [2] = "Greetings! Can I teach you how to turn beast hides into armor?" },
        ["text"] = "Вітаю! Навчити тебе перетворювати шкури звірів на обладунки?",
        ["npcs"] = { [1] = 223, [2] = 1385, [3] = 1466, [4] = 1632, [5] = 3007, [6] = 3008, [7] = 3069, [8] = 3365, [9] = 3549, [10] = 3605, [11] = 3703, [12] = 3967, [13] = 4212, [14] = 4588, [15] = 5040, [16] = 5127, [17] = 5564, [18] = 5784, [19] = 5811, [20] = 7866, [21] = 7867, [22] = 7868, [23] = 7869, [24] = 7870, [25] = 8153, [26] = 11081, [27] = 11083, [28] = 11084, [29] = 11096, [30] = 11097, [31] = 11098 },
        ["roles"] = { ["greeting"] = true },
    },
    [3736361798] = {
        ["english"] = { [1] = "The Gordunni Ogres encroach upon our lands.  We send as many as are willing to face them in the desecrated ruins of Feralas. " },
        ["text"] = "Огри Ґордунні зазіхають на наші землі. Ми посилаємо всіх охочих зустрітися з ними в осквернених руїнах Фераласа. ",
        ["npcs"] = { [1] = 7777 },
        ["roles"] = { ["greeting"] = true },
    },
    [4174350564] = {
        ["english"] = { [1] = "$C, eh? I am Krazek, Baron Revilgaz's secretary. I know everything about the goings on in this jungle and beyond. Perhaps you'd be interested in knowing the going price on oil in Ratchet? No? Looking for work, maybe? I can help you there." },
        ["text"] = "$C, еге ж? Я Кразек, секретар барона Ревілґаза. Я знаю все про те, що коїться в цих джунглях і за їхніми межами. Можливо, тебе зацікавить нинішня ціна на нафту в Брашпилі? Ні? Може, шукаєш роботу? Тут я можу допомогти.",
        ["npcs"] = { [1] = 773 },
        ["roles"] = { ["greeting"] = true },
    },
    [3260106715] = {
        ["english"] = { [1] = "A foul corruption has crept into Westfall.  While I was upholding my duty on the battlefields of Lordaeron these honest farms were overrun and made into hide-outs for thugs and murderers. The People's Militia needs your help." },
        ["text"] = "Мерзенна скверна заповзла до Західного краю. Поки я виконував свій обов'язок на полях битв Лордерону, ці чесні ферми захопили й перетворили на схованки головорізи та вбивці. Народному ополченню потрібна твоя допомога.",
        ["npcs"] = { [1] = 234 },
        ["roles"] = { ["greeting"] = true },
    },
    [2814264718] = {
        ["english"] = { [1] = "This cauldron churns with thick, green bubbles.  Skulls, bones and organs of unknown creatures swim within its viscous broth...$B$BAnd rising lazily to the surface are the skulls of two, once mighty trolls:$B$BGan'zulah and Nezzliok." },
        ["text"] = "У цьому казані клекоче густа зелена маса. Черепи, кістки й органи невідомих істот плавають у в'язкому вариві...$B$BА на поверхню ліниво спливають черепи двох колись могутніх тролів:$B$BҐан'зули та Неззліока.",
        ["npcs"] = {},
        ["roles"] = { ["greeting"] = true },
    },
    [1405186484] = {
        ["english"] = { [1] = "Hail, $N!  Welcome to my humble garden.  The weather has been perfect lately.  Let us hope it holds steady for a ripe harvest." },
        ["text"] = "Вітаю, $N! Ласкаво прошу до мого скромного саду. Останнім часом погода була ідеальною. Сподіваймося, вона такою й лишиться до щедрого врожаю.",
        ["npcs"] = { [1] = 342 },
        ["roles"] = { ["greeting"] = true },
    },
    [2969083125] = {
        ["english"] = { [1] = "The balance of nature is a delicate one, and easily tipped.  Are you brave enough to make things right?" },
        ["text"] = "Рівновага природи крихка, і її легко порушити. Чи вистачить тобі сміливості все виправити?",
        ["npcs"] = { [1] = 3848 },
        ["roles"] = { ["greeting"] = true },
    },
    [3772396621] = {
        ["english"] = { [1] = "Pleased to meetcha, $c. Me name's Roetten. I lead Reclaimers Incorporated.$B$BMe guild and I specialize in aquiring lost goods. We usually hire brave adventurers and send them off to finish tasks for those who aren't able, or don't have the time." },
        ["text"] = "Радий познайомитися, $c. Мене звати Роеттен. Я очолюю «Відновлювачі, інкорпорейтед».$B$BМоя гільдія й я спеціалізуємося на поверненні загублених речей. Зазвичай ми наймаємо сміливих шукачів пригод і відправляємо їх виконувати завдання для тих, хто не може або не має часу.",
        ["npcs"] = { [1] = 5637 },
        ["roles"] = { ["greeting"] = true },
    },
    [3230094497] = {
        ["english"] = { [1] = "Well, hello there. You seem like you wouldn't be opposed to making some coin, hm? I can tell from the look in your eyes. I am Mogul Kebok, overseer of operations in Azeroth, and if it is riches you seek, perhaps I can make arrangements." },
        ["text"] = "Ну, привіт. Схоже, ти не проти трохи заробити, га? Я бачу це по твоїх очах. Я магнат Кебок, наглядач операцій в Азероті, і якщо ти шукаєш багатства, можливо, я зможу дещо влаштувати.",
        ["npcs"] = { [1] = 737 },
        ["roles"] = { ["greeting"] = true },
    },
    [2322882019] = {
        ["english"] = { [1] = "We may not be in open war with the Alliance, but blood is still shed between us." },
        ["text"] = "Може, ми й не ведемо відкритої війни з Альянсом, але кров між нами все ще проливається.",
        ["npcs"] = { [1] = 4791 },
        ["roles"] = { ["greeting"] = true },
    },
    [3411971465] = {
        ["english"] = { [1] = "The heft of an axe, the battlecry of your allies, the spray of blood in your face. These are the things a warrior craves, $n. I will carve out The Barrens with my sword in the name of the Horde." },
        ["text"] = "Вага сокири, бойовий клич союзників, бризки крові на обличчі. Ось чого прагне воїн, $n. Я прорубаю собі шлях крізь Степи мечем в ім'я Орди.",
        ["npcs"] = { [1] = 3337 },
        ["roles"] = { ["greeting"] = true },
    },
    [1133283307] = {
        ["english"] = { [1] = "I don't have much time for idle talk, $N.  I've got to get this bridge rebuilt before the rains come.  I've finished every project on-time and under budget and I'm not about to start slipping now." },
        ["text"] = "У мене немає часу на пусті балачки, $N. Треба відбудувати цей міст до початку дощів. Я завжди завершував усі проєкти вчасно й дешевше кошторису, і не збираюся псувати цю традицію.",
        ["npcs"] = { [1] = 341 },
        ["roles"] = { ["greeting"] = true },
    },
    [2742288938] = {
        ["english"] = { [1] = "Hello, warlock!  Ready for some training?" },
        ["text"] = "Привіт, чорнокнижнику! Готовий до тренування?",
        ["npcs"] = { [1] = 459, [2] = 460, [3] = 461, [4] = 906, [5] = 988, [6] = 2126, [7] = 2127, [8] = 3156, [9] = 3172, [10] = 3324, [11] = 3325, [12] = 3326, [13] = 4563, [14] = 4564, [15] = 4565, [16] = 5171, [17] = 5172, [18] = 5173, [19] = 5495, [20] = 5496, [21] = 5612, [22] = 6251 },
        ["roles"] = { ["greeting"] = true },
    },
    [3025800489] = {
        ["english"] = { [1] = "Greetings, I am Baros Alexston, City Architect of Stormwind." },
        ["text"] = "Вітаю, я Барос Алексстон, міський архітектор Штормовію.",
        ["npcs"] = { [1] = 1646 },
        ["roles"] = { ["greeting"] = true },
    },
    [3094553081] = {
        ["english"] = { [1] = "Greetings, $c. I'm in a bit of a pinch right now, running very low on hides." },
        ["text"] = "Вітаю, $c. Зараз я трохи в скруті — шкури майже закінчилися.",
        ["npcs"] = { [1] = 2094 },
        ["roles"] = { ["greeting"] = true },
    },
    [716342504] = {
        ["english"] = { [1] = "Thrall paid me and my boys well for helping out with the construction of Orgrimmar, so I decided to set up a port here. We do most of our business through Booty Bay and Baron Revilgaz." },
        ["text"] = "Тралл добре заплатив мені й моїм хлопцям за допомогу в будівництві Орґріммара, тож я вирішив заснувати тут порт. Більшість справ ми ведемо через Бухту наживи та барона Ревілґаза.",
        ["npcs"] = { [1] = 3391 },
        ["roles"] = { ["greeting"] = true },
    },
    [1137923040] = {
        ["english"] = { [1] = "Dark forces encroach upon our borders, ancient taints resurface, and new evils emerge to topple the delicate balance of the land. In times of such darkness, we all must be vigilant." },
        ["text"] = "Темні сили підступають до наших кордонів, прадавня скверна знову виринає, а нове зло прагне зруйнувати крихку рівновагу цих земель. У такі темні часи ми всі маємо бути пильними.",
        ["npcs"] = { [1] = 3649 },
        ["roles"] = { ["greeting"] = true },
    },
    [2610143866] = {
        ["english"] = { [1] = "Hail, $C.  The roads of our fair forest are not entirely without peril.  Tread cautiously." },
        ["text"] = "Вітаю, $C. Дороги нашого прекрасного лісу не зовсім безпечні. Ступай обережно.",
        ["npcs"] = { [1] = 2151 },
        ["roles"] = { ["greeting"] = true },
    },
    [3274381641] = {
        ["english"] = { [1] = "If we are to protect nature, then we must embrace its strength.  And we must show this strength to those who would harm the land." },
        ["text"] = "Якщо ми хочемо захистити природу, маємо прийняти її силу. І показати цю силу тим, хто прагне завдати землі шкоди.",
        ["npcs"] = { [1] = 5770 },
        ["roles"] = { ["greeting"] = true },
    },
    [2655577225] = {
        ["english"] = { [1] = "Well, if it isn't a young, bristling $c, no doubt drawn here by talk of my exploits in fields of battle!$B$BNo time for stories now, for there are great, important deeds that need doing!  So if you're looking for glory, then luck shines on you today..." },
        ["text"] = "Ну треба ж, молодий, войовничий $c, без сумніву, прийшов сюди, наслухавшись про мої подвиги на полях битв!$B$BТа зараз не до історій — попереду великі й важливі справи! Тож якщо шукаєш слави, сьогодні тобі щастить...",
        ["npcs"] = { [1] = 1343 },
        ["roles"] = { ["greeting"] = true },
    },
    [1824695936] = {
        ["english"] = { [1] = "Come a little closer.  We have important matters to discuss, you and I.$B$BAnd some of them we don't want everyone to hear..." },
        ["text"] = "Підійди ближче. Нам із тобою треба обговорити важливі справи.$B$BІ деякі з них не призначені для чужих вух...",
        ["npcs"] = { [1] = 4452 },
        ["roles"] = { ["greeting"] = true },
    },
    [3782103987] = {
        ["english"] = { [1] = "The land, the water and the sky are all as one. It is your eyes that deceive you with such separation. The Earthmother is all those things and more." },
        ["text"] = "Земля, вода й небо — одне ціле. Лише твої очі обманюють тебе, показуючи їх розділеними. Матір-Земля — це все це й навіть більше.",
        ["npcs"] = { [1] = 3338 },
        ["roles"] = { ["greeting"] = true },
    },
    [4261552949] = {
        ["english"] = { [1] = "Some people wonder what we're doing out here in the desert.  Well... if I told you, then you'd stay and try to make our profits!" },
        ["text"] = "Дехто дивується, що ми робимо тут, у пустелі. Ну... якби я тобі сказав, ти б лишився й намагався забрати наші прибутки!",
        ["npcs"] = { [1] = 7876 },
        ["roles"] = { ["greeting"] = true },
    },
    [2876583436] = {
        ["english"] = { [1] = "With alchemy you can turn found herbs into healing and other types of potions." },
        ["text"] = "За допомогою алхімії можна перетворювати знайдені трави на цілющі та інші зілля.",
        ["npcs"] = { [1] = 1215, [2] = 1246, [3] = 1386, [4] = 1470, [5] = 2132, [6] = 2391, [7] = 2837, [8] = 3009, [9] = 3184, [10] = 3347, [11] = 3603, [12] = 3964, [13] = 4160, [14] = 4609, [15] = 4611, [16] = 4900, [17] = 5032, [18] = 5177, [19] = 5499, [20] = 5500, [21] = 7948, [22] = 11041, [23] = 11042, [24] = 11044, [25] = 11046, [26] = 11047 },
        ["roles"] = { ["greeting"] = true },
    },
    [2700512824] = {
        ["english"] = { [1] = "I've got a lot going on out here in Desolace, $N. Roetten wants us to pick up some reagents for one of our clients as well as fetch some of these lost items.$B$BSeein' as you're here to help out, why don't we get started?" },
        ["text"] = "У мене тут, у Спустошищі, справ по горло, $N. Роеттен хоче, щоб ми зібрали реагенти для одного з наших клієнтів, а ще розшукали кілька загублених речей.$B$BРаз уже ти тут, щоб допомогти, то чого тягнути?",
        ["npcs"] = { [1] = 5638 },
        ["roles"] = { ["greeting"] = true },
    },
    [1884413886] = {
        ["english"] = { [1] = "Hello, hello!  Welcome to my kitchen, $g sir : m'lady;!  This is where all of the Scarlet Raven Tavern's finest delicacies are made.  Ah, just smell the wonderful aroma!" },
        ["text"] = "Привіт, привіт! Ласкаво прошу до моєї кухні, $gпане:пані;! Саме тут готують найкращі делікатеси таверни «Багряний Ворон». Ах, тільки відчуй цей чудовий аромат!",
        ["npcs"] = { [1] = 272 },
        ["roles"] = { ["greeting"] = true },
    },
    [2695844797] = {
        ["english"] = { [1] = "The Dark Lady has put forth the challenge.  It is up to us to meet it." },
        ["text"] = "Темна Пані кинула виклик. Тепер нам належить його прийняти.",
        ["npcs"] = { [1] = 1518 },
        ["roles"] = { ["greeting"] = true },
    },
    [2375191988] = {
        ["english"] = { [1] = "Greetings, $G lad : lass;. I'm Grelin Whitebeard. I'm here to examine the threat posed by the growing numbers of trolls in Coldridge Valley. What have I found? It's a bit troubling..." },
        ["text"] = "Вітаю, $Gхлопче:дівчино;. Я Ґрелін Білобородий. Я тут, щоб дослідити загрозу від дедалі більшої кількості тролів у Морозній долині. Що я виявив? Дещо тривожне...",
        ["npcs"] = { [1] = 786 },
        ["roles"] = { ["greeting"] = true },
    },
    [116347164] = {
        ["english"] = { [1] = "Hello, hunter!  Ready for some training?" },
        ["text"] = "Привіт, мисливцю! Готовий до тренування?",
        ["npcs"] = { [1] = 895, [2] = 987, [3] = 1231, [4] = 1404, [5] = 3038, [6] = 3039, [7] = 3040, [8] = 3061, [9] = 3065, [10] = 3154, [11] = 3171, [12] = 3352, [13] = 3406, [14] = 3407, [15] = 3596, [16] = 3601, [17] = 3963, [18] = 4138, [19] = 4146, [20] = 4205, [21] = 5115, [22] = 5116, [23] = 5117, [24] = 5501, [25] = 5515, [26] = 5516, [27] = 5517, [28] = 8308, [29] = 10930 },
        ["roles"] = { ["greeting"] = true },
    },
    [1956863725] = {
        ["english"] = { [1] = "Yes yes yes! You're just the $r I'm looking for!\010\010Sit! We have much to discuss!!" },
        ["text"] = "Так-так-так! Ти саме той $r, кого я шукаю!\010\010Сідай! Нам треба багато чого обговорити!!",
        ["npcs"] = { [1] = 3446 },
        ["roles"] = { ["greeting"] = true },
    },
    [3553243032] = {
        ["english"] = { [1] = "Well hello there, citizen. The name's Bluntnose, Magistrate Bluntnose, to be precise. I'm charged with overseeing the well-being of Thelsamar, and believe you me, we could always use another strong set of arms around here!" },
        ["text"] = "Ну, привіт, громадянине. Мене звати Тупоніс, магістрат Тупоніс, якщо точно. Мені доручено дбати про добробут Телсамара, і повір, ще одна пара сильних рук нам завжди стане в пригоді!",
        ["npcs"] = { [1] = 1139 },
        ["roles"] = { ["greeting"] = true },
    },
    [1398928063] = {
        ["english"] = { [1] = "There were thieves everywhere! $b$bIt was horrible.  The cave came down on us.  I think the mining company is all dead, including my brother, the Foreman." },
        ["text"] = "Злодії були всюди! $b$bЦе було жахливо. Печера обвалилася на нас. Гадаю, вся гірнича компанія загинула, разом із моїм братом, наглядачем.",
        ["npcs"] = { [1] = 656 },
        ["roles"] = { ["greeting"] = true },
    },
    [424638854] = {
        ["english"] = { [1] = "Care to learn how to turn the ore that you find into weapons and metal armor?" },
        ["text"] = "Хочеш навчитися перетворювати знайдену руду на зброю та металеві обладунки?",
        ["npcs"] = { [1] = 514, [2] = 957, [3] = 1241, [4] = 1383, [5] = 2836, [6] = 2998, [7] = 3136, [8] = 3174, [9] = 3355, [10] = 3478, [11] = 3557, [12] = 4258, [13] = 4596, [14] = 4605, [15] = 5164, [16] = 5511, [17] = 6299, [18] = 7230, [19] = 7231, [20] = 7232, [21] = 10266, [22] = 10276, [23] = 10277, [24] = 10278, [25] = 11146, [26] = 11177, [27] = 11178 },
        ["roles"] = { ["greeting"] = true },
    },
    [2789640570] = {
        ["english"] = { [1] = "You will be tested many times by the darkness that surrounds our lands, $N. But to ensure you are always prepared, we will often ask tasks of you so you are at the height of your own power.$B$BGo with the Light, and remain virtuous." },
        ["text"] = "Темрява, що оточує наші землі, ще не раз випробовуватиме тебе, $N. Та щоб ти завжди був готовий, ми часто доручатимемо тобі завдання, аби ти лишався на вершині своїх сил.$B$BІди зі Світлом і зберігай чесноту.",
        ["npcs"] = { [1] = 6171 },
        ["roles"] = { ["greeting"] = true },
    },
    [2829611963] = {
        ["english"] = { [1] = "You watch where you step around here, $Gson:lass;.  You might not be a part of our outfit, but that doesn't mean I won't take a cane to you if you fall out of line!" },
        ["text"] = "Дивись, куди ступаєш тут, $Gсинку:дівчино;. Ти, може, й не з нашої ватаги, але це не означає, що я не відлупцюю тебе ціпком, якщо порушиш порядок!",
        ["npcs"] = { [1] = 733 },
        ["roles"] = { ["greeting"] = true },
    },
    [4244743877] = {
        ["english"] = { [1] = "No, Longears isn't my real name.  And I'm not going to tell you what it is, so don't ask." },
        ["text"] = "Ні, Довговух — не моє справжнє ім'я. І я не скажу тобі, яке воно, тож не питай.",
        ["npcs"] = { [1] = 4456 },
        ["roles"] = { ["greeting"] = true },
    },
    [1081346877] = {
        ["english"] = { [1] = "What do you ask of me?" },
        ["text"] = "Чого ти від мене хочеш?",
        ["npcs"] = { [1] = 5598 },
        ["roles"] = { ["greeting"] = true },
    },
    [654386464] = {
        ["english"] = { [1] = "Where Troggs and Leper Gnomes roam stands our home - Gnomeregan.$B$BOur families lost, our homes displaced. Scattered.$B$BOh how I long for the days of carefree Gnomeregan life, but those days are no more. We must make our stand! We must save Gnomeregan!" },
        ["text"] = "Там, де блукають троґґи й прокажені гноми, стоїть наш дім — Ґномреґан.$B$BНаші родини втрачені, наші домівки покинуті. Ми розсіяні.$B$BО, як я сумую за безтурботними днями життя в Ґномреґані, але їх більше немає. Ми маємо вистояти! Ми маємо врятувати Ґномреґан!",
        ["npcs"] = { [1] = 6569 },
        ["roles"] = { ["greeting"] = true },
    },
    [1928965396] = {
        ["english"] = { [1] = "You look as though you have traveled from afar, $r." },
        ["text"] = "Схоже, ти прибув здалеку, $r.",
        ["npcs"] = { [1] = 4048 },
        ["roles"] = { ["greeting"] = true },
    },
    [2904095151] = {
        ["english"] = { [1] = "Hello, paladin!  Ready for some training?" },
        ["text"] = "Привіт, паладине! Готовий до тренування?",
        ["npcs"] = { [1] = 925, [2] = 926, [3] = 927, [4] = 928, [5] = 1232, [6] = 5147, [7] = 5148, [8] = 5149, [9] = 5491, [10] = 5492, [11] = 8140 },
        ["roles"] = { ["greeting"] = true },
    },
    [4148503057] = {
        ["english"] = { [1] = "My vision has darkened, but there are many kinds of sight..." },
        ["text"] = "Мій зір згас, але існує багато способів бачити...",
        ["npcs"] = { [1] = 5878 },
        ["roles"] = { ["greeting"] = true },
    },
    [3741467468] = {
        ["english"] = { [1] = "The Kirin Tor did not heed my warnings!  The Alliance is a sham.  Arugal is a wreckless fool." },
        ["text"] = "Кірін-Тор не дослухався до моїх попереджень! Альянс — фарс. Аруґал — безрозсудний дурень.",
        ["npcs"] = { [1] = 1938 },
        ["roles"] = { ["greeting"] = true },
    },
    [1871388504] = {
        ["english"] = { [1] = "Welcome to the town of Darkshire.  Clerk Daltry at your service.  Can I be of some assistance?" },
        ["text"] = "Ласкаво просимо до Темнокраю. Писар Далтрі до твоїх послуг. Чимось допомогти?",
        ["npcs"] = { [1] = 267 },
        ["roles"] = { ["greeting"] = true },
    },
    [3349643827] = {
        ["english"] = { [1] = "You know, I always wanted to be a Prospector, but I was born with a head for numbers and the Guild decided I would be best suited to keep the books! Studying, studying, every day of my youth..." },
        ["text"] = "Знаєш, я завжди хотів бути старателем, але від народження мав хист до чисел, і Гільдія вирішила, що мені краще вести рахунки! Навчання, навчання — кожен день моєї молодості...",
        ["npcs"] = { [1] = 1105 },
        ["roles"] = { ["greeting"] = true },
    },
    [1590679048] = {
        ["english"] = { [1] = "You have not lived until you have dug deep into the earth." },
        ["text"] = "Ти не жив по-справжньому, доки не копав глибоко в землі.",
        ["npcs"] = { [1] = 1681, [2] = 1701, [3] = 3001, [4] = 3137, [5] = 3175, [6] = 3357, [7] = 3555, [8] = 4254, [9] = 4598, [10] = 5392, [11] = 5513, [12] = 6297, [13] = 8128 },
        ["roles"] = { ["greeting"] = true },
    },
    [846465496] = {
        ["english"] = { [1] = "I have a great deal of work to do.  Are you here to aid me with my research?" },
        ["text"] = "У мене сила-силенна роботи. Ти тут, щоб допомогти з моїми дослідженнями?",
        ["npcs"] = { [1] = 2277 },
        ["roles"] = { ["greeting"] = true },
    },
    [263367325] = {
        ["english"] = { [1] = "Whitereach Post started off as a small hunting camp... Now, everyone wants to set up shop and call this home.$b$b<Motega shrugs his shoulder>" },
        ["text"] = "Білосяжна застава починалася як маленький мисливський табір... А тепер усі хочуть тут оселитися й називати це місце домом.$b$b<Мотеґа знизує плечима>",
        ["npcs"] = { [1] = 10428 },
        ["roles"] = { ["greeting"] = true },
    },
    [3660948698] = {
        ["english"] = { [1] = "Whatcha need, $c?  I trust that you've come out to this wasteland for a reason other than idle chit chat." },
        ["text"] = "Чого тобі, $c? Сподіваюся, ти прийшов у цю пустку з кращої причини, ніж пусті балачки.",
        ["npcs"] = { [1] = 6868 },
        ["roles"] = { ["greeting"] = true },
    },
    [744781935] = {
        ["english"] = { [1] = "Greetings, $c." },
        ["text"] = "Вітаю, $c.",
        ["npcs"] = { [1] = 4498 },
        ["roles"] = { ["greeting"] = true },
    },
    [1430488881] = {
        ["english"] = { [1] = "If you're here for the food, then welcome!  You won't find finer dining in all of Stormwind...or Azeroth!$B$BIf you're here on other matters, then please be brief.  I have a dozen dishes in preparation, and must care for each." },
        ["text"] = "Якщо ти заради їжі — ласкаво прошу! Кращих страв не знайдеш ніде у Штормовії... чи навіть в Азероті!$B$BЯкщо ж маєш інші справи, будь ласка, коротше. У мене готується з десяток страв, і за кожною треба стежити.",
        ["npcs"] = { [1] = 1141 },
        ["roles"] = { ["greeting"] = true },
    },
    [2138598091] = {
        ["english"] = { [1] = "I hope you're well, all things considered.$B$BSit for a spell, and hear my tale.  It's a tragedy, of course, but one I hope will end in revenge!" },
        ["text"] = "Сподіваюся, ти тримаєшся, зважаючи на все.$B$BПрисядь на хвильку й послухай мою історію. Це, звісно, трагедія, але я сподіваюся, вона завершиться помстою!",
        ["npcs"] = { [1] = 1500 },
        ["roles"] = { ["greeting"] = true },
    },
    [3390386283] = {
        ["english"] = { [1] = "Huh?!?  Oh.  You don't look like a Defias thief...or a member of the Night Watch.  Take pity on a poor soul, will ya?" },
        ["text"] = "Га?! О. Ти не схожий ні на злодія Непокірних... ні на члена Нічної варти. Зглянься на бідолаху, га?",
        ["npcs"] = { [1] = 288 },
        ["roles"] = { ["greeting"] = true },
    },
    [3751905394] = {
        ["english"] = { [1] = "Hello! The spirits say you here to aid my chief. Say it loud, they do." },
        ["text"] = "Привіт! Духи кажуть, що ти тут, аби допомогти моєму вождю. Гучно кажуть, еге ж.",
        ["npcs"] = { [1] = 2519 },
        ["roles"] = { ["greeting"] = true },
    },
    [3819111665] = {
        ["english"] = { [1] = "Some can't stand the heat of the Great Forge, but I think the heat is just right.  And it's the best place to do some serious smithwork." },
        ["text"] = "Дехто не витримує жару Великого горна, а на мене він саме такий, як треба. І кращого місця для серйозної ковальської роботи не знайти.",
        ["npcs"] = { [1] = 6031 },
        ["roles"] = { ["greeting"] = true },
    },
    [3622159866] = {
        ["english"] = { [1] = "You must listen, young $c.  Listen to the whisperings in the darkness, for they offer guidance in these troubled times." },
        ["text"] = "Ти мусиш слухати, юний $c. Слухай шепіт у темряві, бо він підказує шлях у ці лихі часи.",
        ["npcs"] = { [1] = 4046 },
        ["roles"] = { ["greeting"] = true },
    },
    [1550595457] = {
        ["english"] = { [1] = "Although we're trudging through a slow period at these ruins, I'm confident it won't last long.  But in the meantime, I could use someone like you.  Would you like to aid the Dwarven Explorers' Guild?" },
        ["text"] = "Хоч у цих руїнах зараз затишшя, я певен, що воно триватиме недовго. А поки мені стане в пригоді хтось на кшталт тебе. Хочеш допомогти Гільдії дворфів-дослідників?",
        ["npcs"] = { [1] = 1344 },
        ["roles"] = { ["greeting"] = true },
    },
    [2870269418] = {
        ["english"] = { [1] = "In the name of Elune, the Sentinels keep vigilant watch over all our lands, from the cobbled streets of Darnassus to the edge of Ashenvale Forest." },
        ["text"] = "В ім'я Елуни Вартові невсипно стережуть усі наші землі — від мощених вулиць Дарнаса до окраїн Ясенедолу.",
        ["npcs"] = { [1] = 3936 },
        ["roles"] = { ["greeting"] = true },
    },
    [4071304925] = {
        ["english"] = { [1] = "What a great day for racing! Oh, who am I kidding? Every day's a great day for racing!" },
        ["text"] = "Який чудовий день для перегонів! Ох, кого я обманюю? Кожен день — чудовий день для перегонів!",
        ["npcs"] = { [1] = 4630 },
        ["roles"] = { ["greeting"] = true },
    },
    [912903955] = {
        ["english"] = { [1] = "Aha! Good day, good day, Master $C! Come, sit down and have a drink. You have an enterprising look in your eye, and I think you'll find speaking to me worth your time..." },
        ["text"] = "Ага! Добридень, добридень, майстре $C! Заходь, сідай та випий чогось. В очах у тебе бачу підприємницьку жилку, і, думаю, розмова зі мною буде варта твого часу...",
        ["npcs"] = { [1] = 253 },
        ["roles"] = { ["greeting"] = true },
    },
    [4062210056] = {
        ["english"] = { [1] = "Stand at attention, soldier!$B$BWINKY! SOUND OFF!" },
        ["text"] = "Струнко, солдате!$B$BВІНКІ! ДОПОВІДАЙ!",
        ["npcs"] = { [1] = 9177 },
        ["roles"] = { ["greeting"] = true },
    },
    [1427623242] = {
        ["english"] = { [1] = "Many tests await a paladin of the Light, $N. Be assured, our paths will cross many times in the future if you remain passionate and hold to those virtues that we praise." },
        ["text"] = "Багато випробувань чекає на паладина Світла, $N. Будь певен: наші шляхи ще не раз перетнуться, якщо ти збережеш завзяття й ті чесноти, які ми шануємо.",
        ["npcs"] = { [1] = 6179 },
        ["roles"] = { ["greeting"] = true },
    },
    [3011405548] = {
        ["english"] = { [1] = "Do not be alarmed, $r.  I have long since passed from this land but I intend no harm to your kind.  I have witnessed too much death in my time.  My only wish now is for peace.  Perhaps you can help my cause." },
        ["text"] = "Не лякайся, $r. Я давно покинув цей світ, але не бажаю зла твоєму народові. За свій час я бачив надто багато смертей. Тепер моє єдине бажання — мир. Можливо, ти допоможеш моїй справі.",
        ["npcs"] = { [1] = 392 },
        ["roles"] = { ["greeting"] = true },
    },
    [2919259769] = {
        ["english"] = { [1] = "It was quite a departure, let me tell you, $c. We were grabbing whatever wasn't nailed down or could be removed quickly. We're a little spare on supplies because of it." },
        ["text"] = "Ох і від'їзд був, скажу тобі, $c. Ми хапали все, що не було прибите цвяхами або що можна було швидко зняти. Через це припасів у нас тепер небагато.",
        ["npcs"] = { [1] = 2860 },
        ["roles"] = { ["greeting"] = true },
    },
    [3847654845] = {
        ["english"] = { [1] = "Greetings, $c. I am the Flamekeeper. During the Midsummer Fire Festival, it is my duty to keep this fire beside me burning brightly. It is an honor to be selected for such a task; I fill it gladly.$b$b How can I help you?" },
        ["text"] = "Вітаю, $c. Я Вартовий Полум'я. Під час Свята Вогню сонцестояння мій обов'язок — підтримувати це полум'я яскравим. Бути обраним для такого завдання — велика честь, і я з радістю її приймаю.$b$b Чим можу допомогти?",
        ["npcs"] = { [1] = 16788 },
        ["roles"] = { ["greeting"] = true },
    },
    [3074096281] = {
        ["english"] = { [1] = "Hello, warrior!  Ready for some training?" },
        ["text"] = "Привіт, воїне! Готовий до тренування?",
        ["npcs"] = { [1] = 911, [2] = 912, [3] = 913, [4] = 914, [5] = 985, [6] = 1229, [7] = 1901, [8] = 2119, [9] = 2131, [10] = 3041, [11] = 3042, [12] = 3043, [13] = 3059, [14] = 3063, [15] = 3153, [16] = 3169, [17] = 3353, [18] = 3354, [19] = 3408, [20] = 3593, [21] = 3598, [22] = 4087, [23] = 4089, [24] = 4593, [25] = 4594, [26] = 4595, [27] = 5113, [28] = 5114, [29] = 5479, [30] = 5480, [31] = 7315, [32] = 8141 },
        ["roles"] = { ["greeting"] = true },
    },
    [2060577617] = {
        ["english"] = { [1] = "At ease, $c. If you are just passing though I suggest you stick to the roads and only travel by day. If your business is here in Darkshire, consider lending your abilities to the Night Watch. Our Skill is unquestionable but our numbers are small." },
        ["text"] = "Вільно, $c. Якщо ти лише проходиш повз, раджу триматися доріг і подорожувати тільки вдень. Якщо ж маєш справи тут, у Темнокраї, подумай, чи не допомогти Нічній варті. Наше вміння не викликає сумнівів, але нас замало.",
        ["npcs"] = { [1] = 264 },
        ["roles"] = { ["greeting"] = true },
    },
    [4197030951] = {
        ["english"] = { [1] = "Well met, $n. It is good to see that $cs like yourself are taking an active part in protecting the groves." },
        ["text"] = "Радий зустрічі, $n. Приємно бачити, що такі $cs, як ти, беруть активну участь у захисті гаїв.",
        ["npcs"] = { [1] = 3567 },
        ["roles"] = { ["greeting"] = true },
    },
    [4156213593] = {
        ["english"] = { [1] = "Well met, $C.  If you're here for business, then get yourself a brew and we'll have ourselves a talk." },
        ["text"] = "Радий зустрічі, $C. Якщо ти у справах, бери кухоль пива й поговоримо.",
        ["npcs"] = { [1] = 381 },
        ["roles"] = { ["greeting"] = true },
    },
    [2640859700] = {
        ["english"] = { [1] = "Hello, $N. Perhaps you have some time to chat?" },
        ["text"] = "Привіт, $N. Може, маєш трохи часу поговорити?",
        ["npcs"] = { [1] = 7900 },
        ["roles"] = { ["greeting"] = true },
    },
    [2255400681] = {
        ["english"] = { [1] = "These Mithril Order guys are sissies." },
        ["text"] = "Ці хлопці з Мітрилового ордену — слабкодухі.",
        ["npcs"] = { [1] = 14567 },
        ["roles"] = { ["greeting"] = true },
    },
    [1615504280] = {
        ["english"] = { [1] = "Welcome to the Tower of Azora, young $C.  I am Theocritus.$B$BDo you have business with me?  Or...do I have business with you, perhaps?" },
        ["text"] = "Ласкаво просимо до вежі Азори, юний $C. Я Теокріт.$B$BУ тебе справа до мене? Чи... можливо, це в мене є справа до тебе?",
        ["npcs"] = { [1] = 313 },
        ["roles"] = { ["greeting"] = true },
    },
    [2574006608] = {
        ["english"] = { [1] = "Ah, you there! I have tasks to give, and I need not waste time explaining their crucial nature. Listen close." },
        ["text"] = "Ага, ти! У мене є для тебе завдання, і я не марнуватиму час на пояснення їхньої надзвичайної важливості. Слухай уважно.",
        ["npcs"] = { [1] = 1499 },
        ["roles"] = { ["greeting"] = true },
    },
    [588615624] = {
        ["english"] = { [1] = "My blessings go to you, $c, and I pray they may guide and protect you during these times of trouble.  Be vigilant, but remain hopeful for peace, for hope is our greatest weapon against the darkness." },
        ["text"] = "Моє благословення з тобою, $c, і я молюся, щоб воно вело та захищало тебе в ці тяжкі часи. Будь пильним, але не втрачай надії на мир, адже надія — наша наймогутніша зброя проти темряви.",
        ["npcs"] = { [1] = 1284 },
        ["roles"] = { ["greeting"] = true },
    },
    [428143360] = {
        ["english"] = { [1] = "Hello, shaman. It is good to see one of my $gbrothers:sisters; here. May I aid you somehow?" },
        ["text"] = "Привіт, $gшамане:шаманко;. Приємно бачити тут $gодного з моїх братів:одну з моїх сестер;. Можу чимось допомогти?",
        ["npcs"] = { [1] = 5906 },
        ["roles"] = { ["greeting"] = true },
    },
    [3841706793] = {
        ["english"] = { [1] = "Welcome to the Thunderbrew Distillery, founded by dear ol' pappy, Arkilus Thunderbrew.  I've been keeping the place running ever since my older brother, Grimbooze, disappeared in a drunken haze a few harvests ago." },
        ["text"] = "Ласкаво просимо до винокурні Громовара, заснованої моїм дорогим татусем Аркілусом Громоваром. Я підтримую справу відтоді, як мій старший брат Грімбуз кілька врожаїв тому зник у п'яному тумані.",
        ["npcs"] = { [1] = 1267 },
        ["roles"] = { ["greeting"] = true },
    },
    [1937025484] = {
        ["english"] = { [1] = "Welcome to our humble abode! It's always nice to see a friendly face. And what strong arms you have. My husband and I are always looking for help around the farm. Now that most the good folk have left, it's hard to find an able body to help out." },
        ["text"] = "Ласкаво просимо до нашої скромної оселі! Завжди приємно бачити дружнє обличчя. І які в тебе міцні руки. Ми з чоловіком завжди шукаємо допомоги по господарству. Тепер, коли більшість добрих людей пішла, важко знайти когось вправного.",
        ["npcs"] = { [1] = 235 },
        ["roles"] = { ["greeting"] = true },
    },
    [1066223488] = {
        ["english"] = { [1] = "Bastards came right at us at night, after we'd gotten a few drinks in us. Otherwise, we could've taken 'em, count on it.$B$BEveryone's dead now... except a few of us." },
        ["text"] = "Покидьки напали на нас уночі, коли ми вже трохи випили. Інакше ми б їх здолали, можеш не сумніватися.$B$BТепер усі мертві... крім кількох із нас.",
        ["npcs"] = { [1] = 2910 },
        ["roles"] = { ["greeting"] = true },
    },
    [1883052515] = {
        ["english"] = { [1] = "Welcome to Kibler's Exotic Pets! How can you help me today??" },
        ["text"] = "Ласкаво просимо до «Екзотичних улюбленців Кіблера»! Чим ти можеш мені сьогодні допомогти??",
        ["npcs"] = { [1] = 10260 },
        ["roles"] = { ["greeting"] = true },
    },
    [2883075030] = {
        ["english"] = { [1] = "If I can get the proper ingredients, we can create some explosives that will not only allow me to damage the Venture's Co.'s operations, but also cause a distraction.$B$BI know you're impressed, but it gets better... I'll tell you more soon enough." },
        ["text"] = "Якщо я дістану потрібні складники, ми зможемо зробити вибухівку, яка не лише зашкодить операціям Торгової компанії, а й спричинить відволікання.$B$BЗнаю, ти вражений, але далі буде ще краще... Скоро розповім більше.",
        ["npcs"] = { [1] = 4077 },
        ["roles"] = { ["greeting"] = true },
    },
    [1416368501] = {
        ["english"] = { [1] = "Welcome to Bonegrip's Runes and Dooms, $c.  You may look, but do not touch.$B$BSome of the knowledge here is not meant for the...uninitiated." },
        ["text"] = "Ласкаво просимо до «Рун і Приречень Кісткохвата», $c. Дивитися можна, торкатися — ні.$B$BДеякі знання тут не призначені для... непосвячених.",
        ["npcs"] = { [1] = 2786 },
        ["roles"] = { ["greeting"] = true },
    },
    [3799766247] = {
        ["english"] = { [1] = "We spent so much of our lives in fight, memories of peaceful times grow evermore distant." },
        ["text"] = "Стільки життя ми провели в боях, що спогади про мирні часи стають дедалі віддаленішими.",
        ["npcs"] = { [1] = 1776 },
        ["roles"] = { ["greeting"] = true },
    },
    [517769209] = {
        ["english"] = { [1] = "Throm'ka, $c. There is little time for talk and much work to be done." },
        ["text"] = "Тром-ка, $c. На балачки часу мало, а роботи багато.",
        ["npcs"] = { [1] = 3139 },
        ["roles"] = { ["greeting"] = true },
    },
    [3002184004] = {
        ["english"] = { [1] = "Ashenvale is a lush forest, brimming with life. It is a pleasure to walk down its secret paths in search of herbs, but one must take care. The forest is not without its dangers." },
        ["text"] = "Ясенеділ — пишний ліс, сповнений життя. Приємно блукати його потаємними стежками в пошуках трав, та слід бути обережним. У лісі не бракує небезпек.",
        ["npcs"] = { [1] = 3847 },
        ["roles"] = { ["greeting"] = true },
    },
    [2890454480] = {
        ["english"] = { [1] = "My brother and I are on a scouting mission, but we are holed up in this farmhouse. The Deathstalkers need your help!" },
        ["text"] = "Ми з братом на розвідці, але застрягли в цьому фермерському будинку. Смертоловам потрібна твоя допомога!",
        ["npcs"] = { [1] = 1950 },
        ["roles"] = { ["greeting"] = true },
    },
    [1686448266] = {
        ["english"] = { [1] = "Back away!  Stay back!  I have a pack full of blastpowder and I'm not afraid to use it!  I'll blow us all away!$B$BOh, never mind.  I thought you were someone else...." },
        ["text"] = "Назад! Не підходь! У мене повний наплічник вибухового пороху, і я не боюся його використати! Рознесу нас усіх!$B$BА, не зважай. Я подумав, що ти хтось інший....",
        ["npcs"] = { [1] = 2785 },
        ["roles"] = { ["greeting"] = true },
    },
    [2908426319] = {
        ["english"] = { [1] = "We at Refuge Pointe hold one of the few remaining patches of Stromgarde territory in the Arathi Highlands.  And we're losing ground...$B$BIf you have words for me, then I hope they are good tidings." },
        ["text"] = "Ми в Опорному пункті утримуємо один із небагатьох клаптиків території Стромґарда, що лишилися у Верховинах Араті. І ми втрачаємо землю...$B$BЯкщо маєш щось сказати, сподіваюся, це добрі новини.",
        ["npcs"] = { [1] = 2700 },
        ["roles"] = { ["greeting"] = true },
    },
    [3107041793] = {
        ["english"] = { [1] = "Hail, traveler.  My eyesight may be poor but I can sense the footsteps of a $c from a mile away.  For years I defended Stormwind with pride but once my eyes failed me, I was forced to retire." },
        ["text"] = "Вітаю, мандрівнику. Зір у мене вже слабкий, та кроки $c я відчую за милю. Багато років я з гордістю захищав Штормовій, але коли очі мене підвели, довелося піти у відставку.",
        ["npcs"] = { [1] = 294 },
        ["roles"] = { ["greeting"] = true },
    },
    [3781627719] = {
        ["english"] = { [1] = "Nothing but trouble in these parts.  I tried to tell that fool Saldean to get out while he still could but he won't hear of it.  But I ain't no fool.  Verna and I are gonna mosey on out as soon as we get this wagon fixed." },
        ["text"] = "У цих краях самі клопоти. Я намагався переконати того дурня Салдіна забратися, поки ще може, але він і слухати не хоче. А я не дурень. Щойно полагодимо цей віз, ми з Верною заберемося звідси.",
        ["npcs"] = { [1] = 237 },
        ["roles"] = { ["greeting"] = true },
    },
    [2778343889] = {
        ["english"] = { [1] = "Troggs! I swear the gods put them in this land only to torment me! Four inches deeper into the mines, then two feet back from the troggs!" },
        ["text"] = "Троґґи! Клянуся, боги поселили їх на цій землі лише для того, щоб мучити мене! Чотири дюйми вглиб шахти — і два фути назад через троґґів!",
        ["npcs"] = { [1] = 1254 },
        ["roles"] = { ["greeting"] = true },
    },
    [1915654990] = {
        ["english"] = { [1] = "To think, the place the Warchief was born and raised lies so close." },
        ["text"] = "Лише подумати: місце, де народився й виріс Вождь, зовсім поруч.",
        ["npcs"] = { [1] = 2229 },
        ["roles"] = { ["greeting"] = true },
    },
    [1800351274] = {
        ["english"] = { [1] = "To hunt a beast, one must know that beast.  One must learn and respect its ways.$B$BTo do otherwise is not to hunt.  To do otherwise is merely to kill." },
        ["text"] = "Щоб полювати на звіра, треба знати цього звіра. Треба вивчити й шанувати його звички.$B$BІнакше це не полювання. Інакше це просто вбивство.",
        ["npcs"] = { [1] = 3441 },
        ["roles"] = { ["greeting"] = true },
    },
    [2891883280] = {
        ["english"] = { [1] = "Through knowledge, may we find salvation." },
        ["text"] = "Через знання нехай прийде спасіння.",
        ["npcs"] = { [1] = 11036 },
        ["roles"] = { ["greeting"] = true },
    },
    [1625092979] = {
        ["english"] = { [1] = "Oy!  You here for a game of knuckles?" },
        ["text"] = "Ой! Ти тут, щоб зіграти в бабки?",
        ["npcs"] = { [1] = 2501 },
        ["roles"] = { ["greeting"] = true },
    },
    [547195740] = {
        ["english"] = { [1] = "We elves have a long history.  Let us hope this history does not return to haunt us." },
        ["text"] = "У нас, ельфів, довга історія. Сподіваймося, вона не повернеться, щоб переслідувати нас.",
        ["npcs"] = { [1] = 3845 },
        ["roles"] = { ["greeting"] = true },
    },
    [3178375607] = {
        ["english"] = { [1] = "This wooden board holds roughly-made wanted posters." },
        ["text"] = "На цій дерев'яній дошці висять грубо зроблені оголошення про розшук.",
        ["npcs"] = {},
        ["roles"] = { ["greeting"] = true },
    },
    [2806813727] = {
        ["english"] = { [1] = "Greetings, $c! Fine day for hunting, wouldn't you say? I've been having more than a little luck with boars, myself. Perhaps you'd like a shot?" },
        ["text"] = "Вітаю, $c! Чудовий день для полювання, чи не так? Мені неабияк щастить на вепрів. Може, й ти хочеш спробувати?",
        ["npcs"] = { [1] = 714 },
        ["roles"] = { ["greeting"] = true },
    },
    [1281711063] = {
        ["english"] = { [1] = "This sty's a little shy of comfy, but it has history, so Stonard must be important to someone. I'd gamble that's why we stay here. It sure ain't for the view--it don't even look like home." },
        ["text"] = "Цей хлів далекий від затишку, зате має історію, тож Камінард, мабуть, комусь таки важливий. Закладаюся, саме тому ми тут і сидимо. Точно не через краєвид — він навіть на дім не схожий.",
        ["npcs"] = { [1] = 5591 },
        ["roles"] = { ["greeting"] = true },
    },
    [265921564] = {
        ["english"] = { [1] = "Thanks to the Warchief, even here in the ruins of our former prison some hope remains, and the Horde rises anew." },
        ["text"] = "Завдяки Вождю навіть тут, серед руїн нашої колишньої в'язниці, лишається надія, і Орда постає знову.",
        ["npcs"] = { [1] = 2706 },
        ["roles"] = { ["greeting"] = true },
    },
    [513118055] = {
        ["english"] = { [1] = "Hey $Gbuddy:ma'am;, do you think you could give me a hand with something?  I'm really in dire straits here..." },
        ["text"] = "Гей, $Gдруже:пані;, може, допоможеш мені з однією справою? Я тут справді в страшній скруті...",
        ["npcs"] = { [1] = 415 },
        ["roles"] = { ["greeting"] = true },
    },
    [664133646] = {
        ["english"] = { [1] = "The Barrens holds a variety of substances for which we, the apothecaries of Lordaeron may find use." },
        ["text"] = "У Степах є чимало речовин, яким ми, аптекарі Лордерону, можемо знайти застосування.",
        ["npcs"] = { [1] = 3390 },
        ["roles"] = { ["greeting"] = true },
    },
    [1918675507] = {
        ["english"] = { [1] = "Hail, $C.  Ill times these are, my friend, for our town is besieged!  The Blackrock Orcs attack from Stonewatch Keep, the Shadowhides loom over the Tower of Ilgalar, and the Redridge Gnoll Pack gathers strength.  I hope you're not here for a holiday..." },
        ["text"] = "Вітаю, $C. Лихі часи настали, друже, наше місто в облозі! Орки Чорного Каменю нападають із фортеці Кам'яної Варти, Тінешкурі чатують біля вежі Ілґалара, а зграя ґнолів Багрянокряжжя набирає сили. Сподіваюся, ти не на відпочинок...",
        ["npcs"] = { [1] = 464 },
        ["roles"] = { ["greeting"] = true },
    },
    [1426864913] = {
        ["english"] = { [1] = "What do you want? I'd be a whole lot happier up in the skies than grounded and yapping with a $r right now.$b$bGuess we can't all get what we want." },
        ["text"] = "Чого тобі? Я був би значно щасливіший у небі, ніж тут, на землі, теревенити зараз із $r.$b$bТа не всім нам дістається те, чого ми хочемо.",
        ["npcs"] = { [1] = 5636 },
        ["roles"] = { ["greeting"] = true },
    },
    [2424137078] = {
        ["english"] = { [1] = "This collection of scrolls contains various logistic and strategic information, as well as coded correspondences." },
        ["text"] = "Ця збірка сувоїв містить різноманітні логістичні й стратегічні відомості, а також зашифроване листування.",
        ["npcs"] = {},
        ["roles"] = { ["greeting"] = true },
    },
    [3392572398] = {
        ["english"] = { [1] = "They're out there!  I can hear them at night, laughing.  Oh, they'll pay!  They...will...pay!!" },
        ["text"] = "Вони там! Я чую, як вони сміються вночі. О, вони заплатять! Вони... заплатять!!",
        ["npcs"] = { [1] = 2500 },
        ["roles"] = { ["greeting"] = true },
    },
    [3070135916] = {
        ["english"] = { [1] = "Can I teach you how to turn the meat you find on beasts into a feast?" },
        ["text"] = "Навчити тебе перетворювати м'ясо, здобуте зі звірів, на справжній бенкет?",
        ["npcs"] = { [1] = 1355, [2] = 1382, [3] = 1430, [4] = 1699, [5] = 3026, [6] = 3067, [7] = 3087, [8] = 3399, [9] = 4210, [10] = 4552, [11] = 5159, [12] = 5482, [13] = 6286, [14] = 8306 },
        ["roles"] = { ["greeting"] = true },
    },
    [3349825308] = {
        ["english"] = { [1] = "There is something you wish to discuss, $c... come, sit by me." },
        ["text"] = "Є щось, що ти хочеш обговорити, $c... підходь, сідай поруч.",
        ["npcs"] = { [1] = 3188 },
        ["roles"] = { ["greeting"] = true },
    },
    [2808555896] = {
        ["english"] = { [1] = "Don't let the heat bother you.  In the Badlands, heat is the least of your worries." },
        ["text"] = "Не зважай на спеку. У Безплідних краях спека — найменша з твоїх турбот.",
        ["npcs"] = { [1] = 5394 },
        ["roles"] = { ["greeting"] = true },
    },
    [3866653664] = {
        ["english"] = { [1] = "Greetings!  Can I teach you how to turn found cloth into cloth armor?" },
        ["text"] = "Вітаю! Навчити тебе перетворювати знайдену тканину на тканинні обладунки?",
        ["npcs"] = { [1] = 1103, [2] = 1300, [3] = 1346, [4] = 1703, [5] = 2399, [6] = 2627, [7] = 2855, [8] = 3004, [9] = 3363, [10] = 3484, [11] = 3523, [12] = 3704, [13] = 4159, [14] = 4193, [15] = 4576, [16] = 4578, [17] = 5041, [18] = 5153, [19] = 5567, [20] = 9584, [21] = 11048, [22] = 11049, [23] = 11050, [24] = 11051, [25] = 11052, [26] = 11557 },
        ["roles"] = { ["greeting"] = true },
    },
    [3225939453] = {
        ["english"] = { [1] = "The tauren are sons and daughters of the Earthmother, and we show respect to all her children.  Even the beasts we slay are cherished, as their bodies give nourishment and their skins provide warmth." },
        ["text"] = "Таурени — сини й доньки Матері-Землі, і ми шануємо всіх її дітей. Навіть звірів, яких убиваємо, ми цінуємо, бо їхні тіла дають поживу, а шкури — тепло.",
        ["npcs"] = { [1] = 3050 },
        ["roles"] = { ["greeting"] = true },
    },
    [1010537513] = {
        ["english"] = { [1] = "The summoning of beings from the chaos that lies beyond our world is essential to the mastery of the warlock arts, $N. I am glad to see the progress you have made." },
        ["text"] = "Виклик істот із хаосу, що лежить за межами нашого світу, є необхідним для опанування мистецтв чорнокнижника, $N. Я радий бачити твій поступ.",
        ["npcs"] = { [1] = 5675 },
        ["roles"] = { ["greeting"] = true },
    },
    [2830413737] = {
        ["english"] = { [1] = "Hey there, $N.$B$BLotwil's not the most perceptive boss I've had. He actually gets really involved with his work. So much so that sometimes his servants don't eat, or get paid.$B$B<Lucien frowns over at Lotwil.>$B$BBut that doesn't mean you should suffer." },
        ["text"] = "Гей, $N.$B$BЛотвіл — не найуважніший начальник із тих, що в мене були. Він справді занурюється у свою роботу. Настільки, що іноді його слуги не отримують ні їжі, ні платні.$B$B<Люсьєн насуплено дивиться на Лотвіла.>$B$BАле це не означає, що й ти маєш страждати.",
        ["npcs"] = { [1] = 2920 },
        ["roles"] = { ["greeting"] = true },
    },
    [2668507098] = {
        ["english"] = { [1] = "Harumph!  As if I don't have enough to do out here in the muck, without all these distractions!" },
        ["text"] = "Гр-р! Наче мені тут у багнюці роботи мало без усіх цих відволікань!",
        ["npcs"] = { [1] = 1217 },
        ["roles"] = { ["greeting"] = true },
    },
    [1254125071] = {
        ["english"] = { [1] = "The spirits are restless!" },
        ["text"] = "Духи неспокійні!",
        ["npcs"] = { [1] = 3995 },
        ["roles"] = { ["greeting"] = true },
    },
    [2240261703] = {
        ["english"] = { [1] = "The Scarlet Crusade is encroaching on our homeland. The foolish zealots do not realize that the loyal servants of The Dark Lady shall see to their demise." },
        ["text"] = "Багряний похід зазіхає на нашу батьківщину. Ці дурні фанатики не розуміють, що вірні слуги Темної Пані подбають про їхню загибель.",
        ["npcs"] = { [1] = 1515 },
        ["roles"] = { ["greeting"] = true },
    },
    [1710984739] = {
        ["english"] = { [1] = "The Royal Apothecary Society shall heed The Dark Lady's call to uncover the New Plague and drive Arthas and his heathen Scourge Army from the world once and for all." },
        ["text"] = "Королівська спілка аптекарів дослухається до заклику Темної Пані, відкриє Нову Чуму й раз і назавжди вижене Артаса та його язичницьке військо Скари з цього світу.",
        ["npcs"] = { [1] = 2055 },
        ["roles"] = { ["greeting"] = true },
    },
    [2084728972] = {
        ["english"] = { [1] = "What what?!?  We all have profit to make... and we won't do it by standing idle." },
        ["text"] = "Що-що?! Усі ми маємо заробляти... а стоячи без діла, грошей не зробиш.",
        ["npcs"] = { [1] = 2498 },
        ["roles"] = { ["greeting"] = true },
    },
    [599233613] = {
        ["english"] = { [1] = "If there's one thing time has taught me it's that no assignment is a dull one.  Protecting the Thandol Span should have been an easy task.  But with the brunt of the army fighting alongside the alliance, we were overwhelmed here and Dun Modr has fallen." },
        ["text"] = "Якщо час чогось мене й навчив, то це того, що нудних завдань не буває. Охорона мосту Тандол мала бути легкою справою. Та основні сили армії воюють разом з Альянсом, тож нас тут здолали, і Дун-Модр упав.",
        ["npcs"] = { [1] = 1071 },
        ["roles"] = { ["greeting"] = true },
    },
    [1025539809] = {
        ["english"] = { [1] = "Information... With our scouts and agents, we control the flow of information in Lordaeron. Scourge movements, their holdings, all underneath our watchful eyes..." },
        ["text"] = "Інформація... Наші розвідники й агенти контролюють потік інформації в Лордероні. Переміщення Скари, їхні володіння — все під нашим пильним оком...",
        ["npcs"] = { [1] = 2121 },
        ["roles"] = { ["greeting"] = true },
    },
    [1269947365] = {
        ["english"] = { [1] = "I don't have time to chat, citizen, but if you're willing to give us a hand against the orcs, then I'll find a use for you." },
        ["text"] = "У мене немає часу на балачки, громадянине, але якщо готовий допомогти нам проти орків, я знайду тобі застосування.",
        ["npcs"] = { [1] = 382 },
        ["roles"] = { ["greeting"] = true },
    },
    [429092261] = {
        ["english"] = { [1] = "The Carevin family fights for victory under the Light. My duty under the Light is to give my life in their battle against against the undead. Master Carevin has tasked me with the extermination of the vile worgen in Duskwood. Perhaps you would assit me?" },
        ["text"] = "Родина Каревінів бореться за перемогу в ім'я Світла. Мій обов'язок перед Світлом — віддати життя в їхній боротьбі проти невмерлих. Майстер Каревін доручив мені винищити мерзенних воргенів у Смерколіссі. Можливо, допоможеш мені?",
        ["npcs"] = { [1] = 663 },
        ["roles"] = { ["greeting"] = true },
    },
    [3947261960] = {
        ["english"] = { [1] = "I'm on quest.  A quest!  A quest for new alloys and harder metals for the greatest invention of all!!" },
        ["text"] = "Я в пошуках. У пошуках! У пошуках нових сплавів і міцніших металів для найвеличнішого винаходу з усіх!!",
        ["npcs"] = { [1] = 6169 },
        ["roles"] = { ["greeting"] = true },
    },
    [873905848] = {
        ["english"] = { [1] = "Something I can help you with, $n? There's a shipment I've got to see to otherwise." },
        ["text"] = "Чимось допомогти, $n? Бо інакше мені треба зайнятися одним вантажем.",
        ["npcs"] = { [1] = 3453 },
        ["roles"] = { ["greeting"] = true },
    },
    [619437853] = {
        ["english"] = { [1] = "The name's Bilgewhizzle, and I am the chief engineer of the Gadgetzan Water Company.  What can I assist you with?" },
        ["text"] = "Мене звати Трюмошип, я головний інженер Водної компанії Пристробляска. Чим можу допомогти?",
        ["npcs"] = { [1] = 7407 },
        ["roles"] = { ["greeting"] = true },
    },
    [2797316379] = {
        ["english"] = { [1] = "The main threat Thrall wishes dealt with is the Burning Blade---members of the Horde that have given their loyalty to the demons. They seek to practice their dark magic and care little for Thrall's visions of the Horde's future here in Kalimdor." },
        ["text"] = "Головна загроза, з якою Тралл хоче покінчити, — Палаючий Клинок: члени Орди, що присягнули демонам. Вони прагнуть практикувати темну магію й не дбають про бачення Тралла щодо майбутнього Орди тут, у Калімдорі.",
        ["npcs"] = { [1] = 5641 },
        ["roles"] = { ["greeting"] = true },
    },
    [2807933663] = {
        ["english"] = { [1] = "The Lich King has brought war against us from the frozen north, and only we of the Argent Dawn stand in his way." },
        ["text"] = "Король-ліч приніс нам війну з крижаної півночі, і лише ми, Сріблястий Світанок, стоїмо на його шляху.",
        ["npcs"] = { [1] = 16361 },
        ["roles"] = { ["greeting"] = true },
    },
    [4012006997] = {
        ["english"] = { [1] = "Greetings, $N. I am Duke Nicholas Zverenhoff of the Argent Dawn." },
        ["text"] = "Вітаю, $N. Я герцог Ніколас Зверенгоф зі Сріблястого Світанку.",
        ["npcs"] = { [1] = 11039 },
        ["roles"] = { ["greeting"] = true },
    },
    [2453101515] = {
        ["english"] = { [1] = "The land has been good to our people, $c. We must be thankful for our good fortune." },
        ["text"] = "Земля була щедрою до нашого народу, $c. Ми маємо бути вдячні за нашу долю.",
        ["npcs"] = { [1] = 2993 },
        ["roles"] = { ["greeting"] = true },
    },
    [1790002294] = {
        ["english"] = { [1] = "The days grow long, and still no end to the conflicts of these lands can be seen. It takes no spell caster to know that much. Take up a blade while you can, $c. War can come to our doors at any time, and if I'm not mistaken, you look to be one who revels in it." },
        ["text"] = "Дні тягнуться довго, а кінця війнам цих земель досі не видно. Щоб зрозуміти це, не треба бути заклиначем. Бери клинок, поки можеш, $c. Війна будь-коли може прийти до нашого порогу, і, якщо я не помиляюся, ти з тих, хто нею насолоджується.",
        ["npcs"] = { [1] = 4485 },
        ["roles"] = { ["greeting"] = true },
    },
    [290280564] = {
        ["english"] = { [1] = "My family boasts the finest collection of jewelry and objects of fine art among all the nobles of Stormwind!$B$BAnd we are always wishing to increase the size our collection..." },
        ["text"] = "Моя родина має найкращу колекцію коштовностей і витворів мистецтва серед усієї знаті Штормовію!$B$BІ ми завжди прагнемо зробити нашу колекцію ще більшою...",
        ["npcs"] = { [1] = 2285 },
        ["roles"] = { ["greeting"] = true },
    },
    [2733607903] = {
        ["english"] = { [1] = "The centaur clans rule the wastes of Desolace. If united, they would be a terrible force. It is then good that the centaur clans are not united but instead bicker and war amongst themselves." },
        ["text"] = "Клани кентаврів панують у пустках Спустошища. Якби вони об'єдналися, стали б жахливою силою. На щастя, клани кентаврів не єдині, а лише сваряться й воюють між собою.",
        ["npcs"] = { [1] = 5412 },
        ["roles"] = { ["greeting"] = true },
    },
    [2325491827] = {
        ["english"] = { [1] = "Eh?  Greetings, young $C.  You're a brave one to find your way here with all those wandering creatures about!$B$BWell now that you are here, maybe you can help an old hermit..." },
        ["text"] = "Еге? Вітаю, юний $C. Треба бути сміливцем, щоб дістатися сюди крізь усіх тих блукаючих істот!$B$BЩо ж, раз уже ти тут, може, допоможеш старому відлюднику...",
        ["npcs"] = { [1] = 289 },
        ["roles"] = { ["greeting"] = true },
    },
    [2146753403] = {
        ["english"] = { [1] = "Greetings, $n. If you bring me necrotic stones from the undead invaders, I can give you access to the stores of the Argent Dawn." },
        ["text"] = "Вітаю, $n. Якщо принесеш мені некротичні камені з невмерлих загарбників, я дам тобі доступ до запасів Сріблястого Світанку.",
        ["npcs"] = { [1] = 16786 },
        ["roles"] = { ["greeting"] = true },
    },
    [2796716529] = {
        ["english"] = { [1] = "Engineering is very simple once you grasp the basics." },
        ["text"] = "Інженерія дуже проста, щойно опануєш основи.",
        ["npcs"] = { [1] = 1676, [2] = 1702, [3] = 2857, [4] = 3290, [5] = 3412, [6] = 3494, [7] = 4586, [8] = 5037, [9] = 5174, [10] = 5518, [11] = 7406, [12] = 8126, [13] = 8736, [14] = 8738, [15] = 10993, [16] = 11017, [17] = 11025, [18] = 11026, [19] = 11028, [20] = 11029, [21] = 11031, [22] = 11037 },
        ["roles"] = { ["greeting"] = true },
    },
    [3031613154] = {
        ["english"] = { [1] = "The Argent Dawn will turn away none who are willing to sacrifice for our cause." },
        ["text"] = "Сріблястий Світанок не відвернеться від жодного, хто готовий жертвувати заради нашої справи.",
        ["npcs"] = { [1] = 16281 },
        ["roles"] = { ["greeting"] = true },
    },
    [2176482836] = {
        ["english"] = { [1] = "The Dark Lady has put the challenge forth.  Now it is up to the Royal Apothecary Society to develop a new plague.  We shall bring Arthas and his wretched army to their knees." },
        ["text"] = "Темна Пані кинула виклик. Тепер Королівська спілка аптекарів має створити нову чуму. Ми поставимо Артаса та його жалюгідне військо на коліна.",
        ["npcs"] = { [1] = 1937 },
        ["roles"] = { ["greeting"] = true },
    },
    [3174799904] = {
        ["english"] = { [1] = "I hope you're here to work, $C.  We have a lot to do and the Horde, the Syndicate and the Ogres aren't going to help us." },
        ["text"] = "Сподіваюся, ти прийшов працювати, $C. Справ багато, а Орда, Синдикат і огри нам не допоможуть.",
        ["npcs"] = { [1] = 2263 },
        ["roles"] = { ["greeting"] = true },
    },
    [3574539059] = {
        ["english"] = { [1] = "So few make it this far, even fewer make it past. Do not become a statistic, $N." },
        ["text"] = "Мало хто доходить так далеко, ще менше — проходять далі. Не стань ще одним числом у статистиці, $N.",
        ["npcs"] = { [1] = 7802 },
        ["roles"] = { ["greeting"] = true },
    },
    [2063686957] = {
        ["english"] = { [1] = "Hello, rogue!  Ready for some training?" },
        ["text"] = "Привіт, розбійнику! Готовий до тренування?",
        ["npcs"] = { [1] = 915, [2] = 916, [3] = 917, [4] = 918, [5] = 1234, [6] = 1411, [7] = 2122, [8] = 2130, [9] = 3155, [10] = 3170, [11] = 3327, [12] = 3328, [13] = 3401, [14] = 3594, [15] = 3599, [16] = 4163, [17] = 4214, [18] = 4215, [19] = 4582, [20] = 4583, [21] = 4584, [22] = 5165, [23] = 5166, [24] = 5167, [25] = 6707, [26] = 13283 },
        ["roles"] = { ["greeting"] = true },
    },
    [1069363334] = {
        ["english"] = { [1] = "Hello, $c.  If you're here, then you must know that Silverpine is saturated with our enemies.  To survive, the Forsaken must drive them back!" },
        ["text"] = "Привіт, $c. Якщо ти тут, то вже знаєш, що Срібнохвой переповнений нашими ворогами. Щоб вижити, Відречені мають відкинути їх назад!",
        ["npcs"] = { [1] = 1952 },
        ["roles"] = { ["greeting"] = true },
    },
    [2381921995] = {
        ["english"] = { [1] = "Overlord Mok'Morokk boss. You do what I say." },
        ["text"] = "Володар Мок'Морокк — головний. Робиш, що я кажу.",
        ["npcs"] = { [1] = 4500 },
        ["roles"] = { ["greeting"] = true },
    },
    [1868345853] = {
        ["english"] = { [1] = "It requires a steady hand to remove the leather from a slain beast." },
        ["text"] = "Щоб зняти шкіру з убитого звіра, потрібна тверда рука.",
        ["npcs"] = { [1] = 1292, [2] = 6287, [3] = 6288, [4] = 6289, [5] = 6290, [6] = 6291, [7] = 6292, [8] = 6295, [9] = 6306, [10] = 6387, [11] = 7087, [12] = 7088, [13] = 7089, [14] = 8144, [15] = 12030 },
        ["roles"] = { ["greeting"] = true },
    },
    [2884098408] = {
        ["english"] = { [1] = "Hello there, $c.  Normally I'd be out on the beat looking after the folk of Stormwind, but a lot of the Stormwind guards are fighting in the other lands.  So here I am, deputized and offering bounties when I'd rather be on patrol..." },
        ["text"] = "Привіт, $c. Зазвичай я патрулював би вулиці й наглядав за мешканцями Штормовію, але багато штормовійських вартових воюють в інших землях. Тож ось я — уповноважений роздавати нагороди за голови, хоча волів би бути в дозорі...",
        ["npcs"] = { [1] = 823 },
        ["roles"] = { ["greeting"] = true },
    },
    [969369199] = {
        ["english"] = { [1] = "For our people to survive, we must study the ways of nature and learn its secrets." },
        ["text"] = "Щоб наш народ вижив, ми маємо вивчати закони природи й пізнавати її таємниці.",
        ["npcs"] = { [1] = 3419 },
        ["roles"] = { ["greeting"] = true },
    },
    [2802539975] = {
        ["english"] = { [1] = "I can teach you how to use a fishing pole to catch fish." },
        ["text"] = "Я можу навчити тебе користуватися вудкою, щоб ловити рибу.",
        ["npcs"] = { [1] = 1651, [2] = 1680, [3] = 1683, [4] = 1700, [5] = 2367, [6] = 2834, [7] = 3028, [8] = 3179, [9] = 3332, [10] = 3607, [11] = 4156, [12] = 4573, [13] = 5161, [14] = 5493, [15] = 5690, [16] = 5938, [17] = 5941, [18] = 7946, [19] = 12032, [20] = 12961, [21] = 14740 },
        ["roles"] = { ["greeting"] = true },
    },
    [4103472711] = {
        ["english"] = { [1] = "Hello!  Can I teach you something?" },
        ["text"] = "Привіт! Навчити тебе дечого?",
        ["npcs"] = { [1] = 3690, [2] = 4732, [3] = 4752, [4] = 4753, [5] = 4772, [6] = 4773, [7] = 7953, [8] = 7954 },
        ["roles"] = { ["greeting"] = true },
    },
    [2794796137] = {
        ["english"] = { [1] = "If you're willing to endure tales that will shiver your timbers and sog your skivvies, then get yourself a drink and sit for a spell..." },
        ["text"] = "Якщо готовий вислухати байки, від яких затремтять щогли й промокнуть підштаники, бери випивку та сідай на хвильку...",
        ["npcs"] = { [1] = 1239 },
        ["roles"] = { ["greeting"] = true },
    },
    [3821790230] = {
        ["english"] = { [1] = "My name is Dran Droffers, and this over here is my dummy son Malton.  If you need salvage, or are looking to sell salvage, then we're who you need to be talking to!" },
        ["text"] = "Мене звати Дран Дрофферс, а це мій тупенький син Мальтон. Якщо тобі потрібен брухт або ти хочеш продати брухт — говорити треба саме з нами!",
        ["npcs"] = { [1] = 6986 },
        ["roles"] = { ["greeting"] = true },
    },
    [1291178949] = {
        ["english"] = { [1] = "The Alliance has many stakes in Desolace, and our hold here is unstable.$B$BWill you help us?" },
        ["text"] = "Альянс має чимало інтересів у Спустошищі, але наше становище тут нестійке.$B$BДопоможеш нам?",
        ["npcs"] = { [1] = 5396 },
        ["roles"] = { ["greeting"] = true },
    },
    [1400554570] = {
        ["english"] = { [1] = "Gaxim is so focused on trying to convince the night elves that his methods are superior that I had no choice but to focus his energies on something--so I unleashed him on the Venture Co.$B$BI remain focused on helping the Charred Vale to the northwest." },
        ["text"] = "Ґаксім так завзято намагається переконати нічних ельфів у перевазі своїх методів, що мені довелося спрямувати його запал на щось інше — тож я спустив його на Торгову компанію.$B$BА я й далі зосереджуюся на допомозі Обвугленій долині на північному заході.",
        ["npcs"] = { [1] = 4080 },
        ["roles"] = { ["greeting"] = true },
    },
    [2228549207] = {
        ["english"] = { [1] = "My business plan never accounted for housing giant kodos... maybe I should have gone into the underwater basket weaving business instead." },
        ["text"] = "Мій бізнес-план ніколи не передбачав житла для велетенських кодо... Може, треба було зайнятися підводним плетінням кошиків.",
        ["npcs"] = { [1] = 11596 },
        ["roles"] = { ["greeting"] = true },
    },
    [220477713] = {
        ["english"] = { [1] = "I have sensed your coming for quite some time, $n.  It was written in the pattern of the stars." },
        ["text"] = "Я давно відчував твоє наближення, $n. Воно було записане у візерунку зірок.",
        ["npcs"] = { [1] = 265 },
        ["roles"] = { ["greeting"] = true },
    },
    [1700162467] = {
        ["english"] = { [1] = "Knowledge is both tool and weapon to those with the will to use it." },
        ["text"] = "Знання — водночас і знаряддя, і зброя для тих, хто має волю ними скористатися.",
        ["npcs"] = { [1] = 2934 },
        ["roles"] = { ["greeting"] = true },
    },
    [3736166040] = {
        ["english"] = { [1] = "I must keep vigilant watch, $n. Auberdine is surrounded by enemies, new and old. Watch your step when you leave this town for I cannot protect you outside of it. That is why I need help with tasks that would take me outside." },
        ["text"] = "Я мушу пильно стерегти, $n. Аубердін оточений ворогами — новими й старими. Дивись під ноги, коли покидатимеш місто, бо за його межами я не зможу тебе захистити. Саме тому мені потрібна допомога із завданнями, що змушують мене виходити назовні.",
        ["npcs"] = { [1] = 3657 },
        ["roles"] = { ["greeting"] = true },
    },
    [1488317340] = {
        ["english"] = { [1] = "It's dark times that have come, $c... All too soon will we lose everything... When the Light will forsake all but those who truly walk under the Light." },
        ["text"] = "Темні часи настали, $c... Дуже скоро ми втратимо все... Коли Світло покине всіх, крім тих, хто по-справжньому йде шляхом Світла.",
        ["npcs"] = { [1] = 633 },
        ["roles"] = { ["greeting"] = true },
    },
    [3673546801] = {
        ["english"] = { [1] = "Over here, you worthless...! If you want to do something useful, listen quick!" },
        ["text"] = "Сюди, нікчемо...! Якщо хочеш зробити щось корисне, слухай швидко!",
        ["npcs"] = { [1] = 1719 },
        ["roles"] = { ["greeting"] = true },
    },
    [3073825307] = {
        ["english"] = { [1] = "Aha!  Did you see that!  I think this new auto-spanner is going to do just the trick for my new influx manifold design." },
        ["text"] = "Ага! Бачиш це?! Гадаю, цей новий автоключ саме те, що треба для моєї нової конструкції впускного колектора.",
        ["npcs"] = { [1] = 4454 },
        ["roles"] = { ["greeting"] = true },
    },
    [3773802348] = {
        ["english"] = { [1] = "The quest for wealth is the only goal for a respectable goblin.$B$BWell, maybe wealth... and a big, loud death!" },
        ["text"] = "Прагнення багатства — єдина гідна мета для поважного гобліна.$B$BНу, може, багатство... і велика, гучна смерть!",
        ["npcs"] = { [1] = 9536 },
        ["roles"] = { ["greeting"] = true },
    },
    [3532558324] = {
        ["english"] = { [1] = "Curse that Brewers' League! They have access to all the best ingredients, while we're stuck here grubbing for grain and hops!$B$BI really would like to give them some bitter tasting justice..." },
        ["text"] = "Будь проклята та Ліга броварів! У них є доступ до найкращих складників, а ми тут змушені порпатися в зерні та хмелі!$B$BЯ б залюбки пригостив їх добрячою порцією гіркої справедливості...",
        ["npcs"] = { [1] = 1374 },
        ["roles"] = { ["greeting"] = true },
    },
    [724380260] = {
        ["english"] = { [1] = "Greetings, $C. Be wary as you travel east toward The Bulwark. Recent surveillance reports indicate increased Scourge activity in that area, so exercise caution." },
        ["text"] = "Вітаю, $C. Будь обережний, прямуючи на схід до Валу. Останні розвідувальні звіти свідчать про посилену активність Скари в тій місцевості, тож пильнуй.",
        ["npcs"] = { [1] = 1495 },
        ["roles"] = { ["greeting"] = true },
    },
    [510962601] = {
        ["english"] = { [1] = "Hello, mage!  Ready for some training?" },
        ["text"] = "Привіт, магу! Готовий до тренування?",
        ["npcs"] = { [1] = 198, [2] = 328, [3] = 331, [4] = 944, [5] = 1228, [6] = 2124, [7] = 2128, [8] = 3047, [9] = 3048, [10] = 3049, [11] = 4566, [12] = 4567, [13] = 4568, [14] = 5144, [15] = 5145, [16] = 5146, [17] = 5497, [18] = 5498, [19] = 5880, [20] = 5882, [21] = 5883, [22] = 5884, [23] = 5885, [24] = 7311, [25] = 7312 },
        ["roles"] = { ["greeting"] = true },
    },
    [2655628882] = {
        ["english"] = { [1] = "How perfect of you to come by, $c.$B$BMy name is Lotwil Veriatus, founding member of the Enlightened Assembly of Arcanology, Alchemy, and Engineering Sciences: we seek to blend the intelligent sciences of Azeroth together into one comprehensive school." },
        ["text"] = "Як доречно, що ти зайшов, $c.$B$BМене звати Лотвіл Веріатус, я співзасновник Просвітленого товариства арканології, алхімії та інженерних наук: ми прагнемо об'єднати розумні науки Азероту в одну всеохопну школу.",
        ["npcs"] = { [1] = 2921 },
        ["roles"] = { ["greeting"] = true },
    },
    [778075358] = {
        ["english"] = { [1] = "I was bred and educated for public service. A representative of the people. My skill was not in arms or crafts, but in words and persuasion" },
        ["text"] = "Мене виховали й навчили служити громаді. Бути представником народу. Моє вміння було не у зброї чи ремеслі, а у словах і переконанні.",
        ["npcs"] = { [1] = 1977 },
        ["roles"] = { ["greeting"] = true },
    },
    [4176895134] = {
        ["english"] = { [1] = "Hey there, friend.  My name's Remy.$BI'm from Redridge to the east, and came here looking for business, looking for business.  You got any...got any??" },
        ["text"] = "Гей, друже. Мене звати Ремі.$BЯ зі Східного Багрянокряжжя, прийшов сюди шукати справу, шукати справу. У тебе є щось... щось є??",
        ["npcs"] = { [1] = 241 },
        ["roles"] = { ["greeting"] = true },
    },
    [2147876200] = {
        ["english"] = { [1] = "Dear $g boy : girl;, you have arrived just in time to assist the Kargath Expeditionary Force." },
        ["text"] = "$gЛюбий хлопче:Люба дівчино;, ти саме вчасно, щоб допомогти експедиційному корпусу Карґата.",
        ["npcs"] = { [1] = 9078 },
        ["roles"] = { ["greeting"] = true },
    },
    [3789774017] = {
        ["english"] = { [1] = "Eh?  You have business with Nimboya?" },
        ["text"] = "Еге? У тебе справа до Німбої?",
        ["npcs"] = { [1] = 2497 },
        ["roles"] = { ["greeting"] = true },
    },
    [165890012] = {
        ["english"] = { [1] = "I, Arynia Cloudsbreak, have been tasked with protecting the sanctity of the Oracle Grove." },
        ["text"] = "Я, Аринія Хмаролом, отримала завдання оберігати святість Гаю Оракула.",
        ["npcs"] = { [1] = 3519 },
        ["roles"] = { ["greeting"] = true },
    },
    [2350501753] = {
        ["english"] = { [1] = "The Outrunners' duty is to ensure the safety of those who travel across the plains of Mulgore. Those that would threaten the safety of the tauren homeland risk punishment at our hands." },
        ["text"] = "Обов'язок Далекоходців — дбати про безпеку тих, хто мандрує рівнинами Мулґора. Ті, хто загрожує безпеці батьківщини тауренів, ризикують отримати покарання від наших рук.",
        ["npcs"] = { [1] = 2988 },
        ["roles"] = { ["greeting"] = true },
    },
    [458719135] = {
        ["english"] = { [1] = "I welcome you back, $n." },
        ["text"] = "Радий знову тебе бачити, $n.",
        ["npcs"] = { [1] = 5887 },
        ["roles"] = { ["greeting"] = true },
    },
    [1738774350] = {
        ["english"] = { [1] = "Keep the door closed, $C.  Never know when the Dark Riders will be passing through again." },
        ["text"] = "Тримай двері зачиненими, $C. Ніколи не знаєш, коли Темні вершники знову проїдуть повз.",
        ["npcs"] = { [1] = 273 },
        ["roles"] = { ["greeting"] = true },
    },
    [2561643286] = {
        ["english"] = { [1] = "This had better be good..." },
        ["text"] = "Сподіваюся, це щось справді важливе...",
        ["npcs"] = { [1] = 3339 },
        ["roles"] = { ["greeting"] = true },
    },
    [3616205477] = {
        ["english"] = { [1] = "Some people think the swamp's no good... no good, they say." },
        ["text"] = "Дехто каже, що болото ні на що не годиться... не годиться, кажуть.",
        ["npcs"] = { [1] = 4792 },
        ["roles"] = { ["greeting"] = true },
    },
    [36973713] = {
        ["english"] = { [1] = "Like Teldrassil itself, Dolanaar embraces those who embrace the land." },
        ["text"] = "Як і сам Тельдрассіль, Доланаар приймає тих, хто приймає землю.",
        ["npcs"] = { [1] = 2083 },
        ["roles"] = { ["greeting"] = true },
    },
    [279528694] = {
        ["english"] = { [1] = "Yarrr... ye best not be trifling with my time, matey!" },
        ["text"] = "Йо-хо-хо... не смій марнувати мій час, приятелю!",
        ["npcs"] = { [1] = 2546 },
        ["roles"] = { ["greeting"] = true },
    },
    [1648307167] = {
        ["english"] = { [1] = "I am Bolvar Fordragon, Highlord of Stormwind." },
        ["text"] = "Я Болвар Фордраґон, верховний лорд Штормовію.",
        ["npcs"] = { [1] = 1748 },
        ["roles"] = { ["greeting"] = true },
    },
    [2187642626] = {
        ["english"] = { [1] = "Hmm... I can plug this wire in here and that will power the fizzletan gear, but then the hydrophlange will need an alternate power source... Maybe I can... Oh, hello! Hey, want to help me try a new invention?" },
        ["text"] = "Гм... Якщо під'єднати цей дріт сюди, він живитиме шестерню Фіззлетана, але тоді гідрофланжу знадобиться інше джерело живлення... Може, я... О, привіт! Гей, хочеш допомогти мені випробувати новий винахід?",
        ["npcs"] = { [1] = 3666 },
        ["roles"] = { ["greeting"] = true },
    },
    [3164019230] = {
        ["english"] = { [1] = "Here, let me show you how to bind those wounds...." },
        ["text"] = "Ось, дозволь покажу, як перев'язувати ці рани....",
        ["npcs"] = { [1] = 2326, [2] = 2327, [3] = 2329, [4] = 2798, [5] = 3181, [6] = 3373, [7] = 4211, [8] = 4591, [9] = 5150, [10] = 5759, [11] = 5939, [12] = 5943, [13] = 6094 },
        ["roles"] = { ["greeting"] = true },
    },
    [2360922848] = {
        ["english"] = { [1] = "Hail, $c. In my years I have seen many eager tauren who wish to prove their worth to the tribe. It should not be forgotten that eagerness is no substitute for wisdom and experience." },
        ["text"] = "Вітаю, $c. За свої роки я бачив чимало запальних тауренів, які прагнули довести племені свою цінність. Не слід забувати: запал не замінить мудрості й досвіду.",
        ["npcs"] = { [1] = 2981 },
        ["roles"] = { ["greeting"] = true },
    },
    [2306058895] = {
        ["english"] = { [1] = "Hello, shaman!  Ready for some training?" },
        ["text"] = "Привіт, шамане! Готовий до тренування?",
        ["npcs"] = { [1] = 986, [2] = 3030, [3] = 3031, [4] = 3032, [5] = 3062, [6] = 3066, [7] = 3157, [8] = 3173, [9] = 3344, [10] = 3403, [11] = 13417 },
        ["roles"] = { ["greeting"] = true },
    },
    [162972790] = {
        ["english"] = { [1] = "Siege engines are the pride of every pilot!" },
        ["text"] = "Облогові машини — гордість кожного пілота!",
        ["npcs"] = { [1] = 2092 },
        ["roles"] = { ["greeting"] = true },
    },
    [1414884557] = {
        ["english"] = { [1] = "Hello, good $gsir:lady;.  Have a seat, and a meal if you're hungry.  Don't fret if I look busy with my needlework - I'm listening to you..." },
        ["text"] = "Вітаю, $gдобрий пане:добра пані;. Сідай і поїж, якщо $gголодний:голодна;. Не зважай, що я зайнятий шиттям — я тебе слухаю...",
        ["npcs"] = { [1] = 278 },
        ["roles"] = { ["greeting"] = true },
    },
    [1135538967] = {
        ["english"] = { [1] = "Searching for herbs requires both knowledge and instinct." },
        ["text"] = "Пошук трав вимагає і знань, і чуття.",
        ["npcs"] = { [1] = 812, [2] = 908, [3] = 1218, [4] = 1458, [5] = 1473, [6] = 2114, [7] = 2390, [8] = 2856, [9] = 3013, [10] = 3185, [11] = 3404, [12] = 3604, [13] = 3965, [14] = 4204, [15] = 4614, [16] = 4898, [17] = 5137, [18] = 5502, [19] = 5566, [20] = 8146, [21] = 12025 },
        ["roles"] = { ["greeting"] = true },
    },
    [2457308518] = {
        ["english"] = { [1] = "If we are to make our place in this world, then we will do so through study, and through the will to ignore our fading human instincts." },
        ["text"] = "Якщо ми хочемо знайти своє місце в цьому світі, то зробимо це через навчання й волю ігнорувати наші згасаючі людські інстинкти.",
        ["npcs"] = { [1] = 5204 },
        ["roles"] = { ["greeting"] = true },
    },
    [1525289384] = {
        ["english"] = { [1] = "The wind whispers to those who listen...$B$BDo you hear it?" },
        ["text"] = "Вітер шепоче тим, хто вміє слухати...$B$BТи чуєш?",
        ["npcs"] = { [1] = 3616 },
        ["roles"] = { ["greeting"] = true },
    },
    [888015973] = {
        ["english"] = { [1] = "Corruption sneaks into nature's grove. The forest must be protected at all costs." },
        ["text"] = "Скверна підкрадається до природного гаю. Ліс треба захистити за будь-яку ціну.",
        ["npcs"] = { [1] = 2930 },
        ["roles"] = { ["greeting"] = true },
    },
}
for key, row in pairs(rows) do addonTable.gossip_hashed.rows[key] = row end
