local _, addonTable = ...

local client_skills = {
    ["Affliction"] = "Страждання",
    ["All - Specializations"] = "Всі - Спеціалізації",
    ["Arcane"] = "Таємне",
    ["Assassination"] = "Ліквідація",
    ["Astral Perfect Victory"] = "Астральна Досконала Перемога",
    ["Balance"] = "Баланс",
    ["Beast Mastery"] = "Володіння звірами",
    ["Companions"] = "Супутники",
    ["Comprehension"] = "Розуміння",
    ["Demonology"] = "Демонологія",
    ["Destruction"] = "Знищення",
    ["Discipline"] = "Дисципліна",
    ["Dwarven Racial"] = "Расова здібність дворфів",
    ["Elemental Combat"] = "Стихійний бій",
    ["Engraving"] = "Рунографія",
    ["Enhancement"] = "Покращення",
    ["Explorer Imp"] = "Імп-дослідник",
    ["Feral Combat"] = "Дикий бій",
    ["Fire"] = "Пожежа",
    ["Galestrider Riding"] = "Верхова їзда на галасливому вершнику",
    ["GENERIC (DND)"] = "ЗАГАЛЬНИЙ (DND)",
    ["Herbalism"] = "Фітотерапія",
    ["Holy"] = "Святий",
    ["Horse Riding"] = "Верхова їзда",
    ["Kodo Riding"] = "Верхова їзда Кодо",
    ["Language: Common"] = "Мова: Загальна",
    ["Language: Darnassian"] = "Мова: Дарнасійська",
    ["Language: Demon Tongue"] = "Мова: демонічна",
    ["Language: Draconic"] = "Мова: драконяча",
    ["Language: Dwarven"] = "Мова: дворфійська",
    ["Language: Gnomish"] = "Мова: гномська",
    ["Language: Gutterspeak"] = "Мова: низька говірка",
    ["Language: Old Tongue"] = "Мова: Стара мова",
    ["Language: Orcish"] = "Мова: оркська",
    ["Language: Taurahe"] = "Мова: Таурахе",
    ["Language: Thalassian"] = "Мова: таласійська",
    ["Language: Titan"] = "Мова: титанська",
    ["Language: Troll"] = "Мова: трольська",
    ["Lockpicking"] = "Відмикання замків",
    ["Marksmanship"] = "Стрільба",
    ["Mounts"] = "Кріплення",
    ["Night Elf Racial"] = "Расова здібність нічних ельфів",
    ["Orc Racial"] = "Расова здібність орків",
    ["Pet - Bat"] = "Улюбленець - Кажан",
    ["Pet - Bear"] = "Улюбленець - Ведмідь",
    ["Pet - Bird of Prey"] = "Улюбленець - Хижий птах",
    ["Pet - Boar"] = "Улюбленець - Кабан",
    ["Pet - Carrion Bird"] = "Улюбленець - Птах-падаль",
    ["Pet - Cat"] = "Улюбленець - Кіт",
    ["Pet - Core Hound"] = "Улюбленець - Гончак надр",
    ["Pet - Crab"] = "Улюбленець - Краб",
    ["Pet - Crocilisk"] = "Улюбленець - Кроциліск",
    ["Pet - Doomguard"] = "Улюбленець - Стражник Долі",
    ["Pet - Event - Remote Control"] = "Улюбленець - Подія - Дистанційне керування",
    ["Pet - Felguard"] = "Улюбленець - Страж Скверни",
    ["Pet - Felhunter"] = "Улюбленець - Мисливець Скверни",
    ["Pet - Fox"] = "Улюбленець - Лисиця",
    ["Pet - Generic"] = "Улюбленець - загальний",
    ["Pet - Gorilla"] = "Улюбленець - Горила",
    ["Pet - Hyena"] = "Улюбленець - Гієна",
    ["Pet - Imp"] = "Улюбленець - Імп",
    ["Pet - Infernal"] = "Улюбленець - Пекельний",
    ["Pet - Raptor"] = "Улюбленець - Раптор",
    ["Pet - Scorpid"] = "Улюбленець - Скорпід",
    ["Pet - Spider"] = "Улюбленець - Павук",
    ["Pet - Succubus"] = "Улюбленець - Суккуб",
    ["Pet - Tallstrider"] = "Улюбленець - Довгоніг",
    ["Pet - Turtle"] = "Улюбленець - Черепаха",
    ["Pet - Voidwalker"] = "Улюбленець - Вартовий Безодні",
    ["Pet - Wind Serpent"] = "Улюбленець - Вітряний Змій",
    ["Pet - Wolf"] = "Улюбленець - Вовк",
    ["Racial - Gnome"] = "Расова здібність — гном",
    ["Racial - Human"] = "Расова здібність — людина",
    ["Racial - Troll"] = "Расова здібність — троль",
    ["Racial - Undead"] = "Расова здібність — невмерлий",
    ["Raptor Riding"] = "Верхова їзда на рапторі",
    ["Retribution"] = "Відплата",
    ["Riding"] = "Верхова їзда",
    ["Runes"] = "Руни",
    ["Shadow Magic"] = "Магія тіней",
    ["Skyborne Racial"] = "Расова здібність небесників",
    ["Survival"] = "Виживання",
    ["Swimming"] = "Плавання",
    ["Tauren Racial"] = "Расова здібність тауренів",
    ["Test Profession [DNT]"] = "Тестова професія [DNT]",
    ["Tiger Riding"] = "Верхова їзда на тигрі",
    ["Undead Horsemanship"] = "Верхова їзда нежиті",
    ["Wolf Riding"] = "Верхова їзда на вовку",
}
if addonTable.forever_catalog then
    addonTable.forever_catalog.register_ui_source(
        "client_domains_skills", "validated_legacy", client_skills, 300)
else
    addonTable.forever_ui = addonTable.forever_ui or {}
    for english, ukrainian in pairs(client_skills) do
        if addonTable.forever_ui[english] == nil then
            addonTable.forever_ui[english] = ukrainian
        end
    end
end

