local _, addonTable = ...

-- Camelot's Game Menu and Settings pages are not part of ClassicUA's legacy
-- GlobalStrings subset. Keep these as display-only translations: the actual
-- Blizzard globals must remain English because Camelot uses some as data keys.
local settings = {
    ["Automatically exit Away mode upon moving or talking."] =
        "Автоматично виходити з режиму «Відійшов» після руху або початку розмови.",
    -- Game menu and Settings navigation
    ["Game Menu"] = "Меню гри",
    ["Return to Game"] = "Повернутися до гри",
    ["Settings"] = "Налаштування",
    ["Options"] = "Налаштування",
    ["Edit Mode"] = "Режим редагування",
    ["Macros"] = "Макроси",
    ["AddOns"] = "Аддони",
    ["Support"] = "Підтримка",
    ["Log Out"] = "Вийти з обл. запису",
    ["Exit Game"] = "Вийти з гри",
    ["Issue Reporter"] = "Звітувати про проблему",
    ["Search Settings"] = "Пошук налаштувань",
    ["Search"] = "Пошук",
    ["System"] = "Система",
    ["Gameplay"] = "Ігровий процес",
    ["Accessibility"] = "Доступність",
    ["General"] = "Загальні",
    ["Graphics"] = "Графіка",
    ["Advanced"] = "Розширені",
    ["Advanced Options"] = "Розширені налаштування",
    ["<Shift-Click to Automatically Enable This Setting>"] =
        "<Shift + клацання — автоматично ввімкнути цей параметр>",

    -- Edit Mode (build 1.60.1.70009). The generated GlobalStrings catalog
    -- contains several literal or machine-translated labels for this surface.
    ["Archaeology Bar"] = "Смуга археології",
    ["Arena Frames"] = "Рамки арени",
    ["Character Specific Layout"] = "Макет персонажа",
    ["Encounter Bar"] = "Смуга сутички",
    ["Experience Bar"] = "Смуга досвіду",
    ["Pet Bar"] = "Панель улюбленця",
    ["Pet Frame"] = "Рамка улюбленця",
    ["Possess Bar"] = "Панель керування",
    ["Stance Bar"] = "Панель стійок",
    ["Totem Bar"] = "Панель тотемів",
    ["Equipment Durability"] = "Міцність спорядження",
    ["Damage Meter"] = "Лічильник шкоди",
    ["Buff Settings"] = "Налаштування підсилень",
    ["Arena Enemy Frames Settings"] = "Налаштування рамок суперників на арені",
    ["Raid Frame Settings"] = "Налаштування рейдових рамок",
    ["Name the New Layout"] = "Назвіть новий макет",
    ["Reset To Default Position"] = "Повернути в типове положення",
    ["Hide Bar Art"] = "Приховати оформлення панелі",
    ["Bar Visible"] = "Видимість панелі",
    ["Icon Padding"] = "Відступ між значками",
    ["Icon Wrap"] = "Перенесення значків",
    ["Bag Padding"] = "Відступ між сумками",
    ["Show Cast Time"] = "Показувати час застосування",
    ["Bar Size"] = "Розмір смуги",
    ["Bar Width"] = "Ширина смуги",
    ["Bar Height"] = "Висота смуги",
    ["Background"] = "Тло",
    ["Padding"] = "Відступ",
    ["Frame Height"] = "Висота рамки",
    ["Frame Width"] = "Ширина рамки",
    ["Frame Size"] = "Розмір рамки",
    ["Show Spec Icon"] = "Показувати значок спеціалізації",
    ["Overall Size"] = "Загальний розмір",
    ["Bars"] = "Смуги",
    ["Active Encounter"] = "Активна сутичка",
    ["Order"] = "Порядок",
    ["Reverse"] = "Зворотний",
    ["Top"] = "Вгорі",
    ["Rotate Minimap"] = "Обертати мінікарту",
    ["Hide Alternate Power Bar"] = "Приховати альтернативну смугу ресурсу",
    ["Hide Power Bar"] = "Приховати смугу ресурсу",
    ["Power Bar Height"] = "Висота смуги ресурсу",
    ["Show Time"] = "Показувати час",
    ["Buffs On Top"] = "Підсилення вгорі",
    ["Buff Size"] = "Розмір підсилень",
    ["Cast Bar on Side"] = "Смуга застосування збоку",
    ["Cast Bar Underneath"] = "Смуга застосування знизу",
    ["Display Border"] = "Показувати рамку",
    ["Use Larger Frame"] = "Використовувати більшу рамку",
    ["Switch"] = "Перемкнути",
    ["Vehicle Exit Button"] = "Кнопка виходу з транспорту",
    ["Vehicle Seats"] = "Місця в транспорті",
    ["%s Specific"] = "Для персонажа %s",
    ["%s (Preset)"] = "%s (готовий макет)",
    ["Are you sure you want to delete the layout|n%s?"] =
        "Ви справді хочете видалити макет|n%s?",
    ["A max of %d character layouts and %d account layouts are allowed"] =
        "Дозволено щонайбільше %d макетів персонажа та %d макетів облікового запису",
    ["Only %d account wide layouts are allowed. Check the box to save a character specific layout"] =
        "Дозволено щонайбільше %d макетів облікового запису. Установіть прапорець, щоб зберегти макет персонажа",
    ["Only %d character specific layouts are allowed. Uncheck the box to save an account wide layout"] =
        "Дозволено щонайбільше %d макетів персонажа. Зніміть прапорець, щоб зберегти макет облікового запису",
    ["The Personal Resource Display doesn't show an Alternate Power Bar for your Class and current Specialization."] =
        "Індикатор особистих ресурсів не показує смугу альтернативного ресурсу для вашого класу й поточної спеціалізації.",
    ["The Personal Resource Display doesn't show any Class Resources for your Class and current Specialization."] =
        "Індикатор особистих ресурсів не показує ресурси вашого класу й поточної спеціалізації.",
    ["# Rows"] = "Кількість рядків",
    ["# Columns"] = "Кількість стовпців",
    ["[PH] Buffs On Right"] = "[PH] Підсилення праворуч",
    ["[PH] Buffs On Top"] = "[PH] Підсилення вгорі",
    ["Big Defensive Size"] = "Розмір сильних захисних ефектів",
    ["Network"] = "Мережа",
    ["Sound"] = "Звук",
    ["Voice Chat"] = "Голосовий чат",
    ["Controls"] = "Керування",
    ["Combat"] = "Бій",
    ["Action Bars"] = "Панелі дій",
    ["Names"] = "Імена",
    ["Interface"] = "Інтерфейс",
    ["Raid Frames"] = "Рейдові рамки",
    ["Social"] = "Спілкування",
    ["Tutorials"] = "Навчання",
    ["Keybindings"] = "Призначення клавіш",
    ["Key Bindings"] = "Призначення клавіш",
    ["Mouse"] = "Миша",
    ["Camera"] = "Камера",
    ["Languages"] = "Мови",
    ["Languages and Social"] = "Мови та спілкування",
    ["Audio"] = "Аудіо",
    ["Audio Assist"] = "Допомога зі звуком",
    ["Colors"] = "Кольори",
    ["Gamepad (Alpha)"] = "Геймпад (альфа)",
    ["Nameplates"] = "Індикатори імен",
    ["Nameplate Information"] = "Відомості на індикаторах",
    ["Cast Bar Information"] = "Смуга заклять",
    ["Enemy NPC Buffs/Debuffs"] = "Ефекти ворожих істот",
    ["Enemy Player Buffs/Debuffs"] = "Ефекти ворожих гравців",
    ["Friendly Player Buffs/Debuffs"] = "Ефекти союзників",
    ["All NPCs: Display names for all NPCs"] =
        "Усі НПЦ: показувати імена всіх НПЦ.",
    ["None: Do not display names for any NPCs"] =
        "Немає: не показувати імена жодних НПЦ.",
    ["Quest NPCs: Display names for NPCs involved with quests, as well as tracked NPCs using the minimap tracker."] =
        "Квестові НПЦ: показувати імена НПЦ, пов'язаних із завданнями, а також НПЦ, яких відстежує мінімапа.",
    ["Hostile, Quest, and Interactive NPCs: Display names for hostile NPC's, those NPCs involved with quests or being tracked, and NPC's you can interact with."] =
        "Ворожі, квестові та інтерактивні НПЦ: показувати імена ворожих НПЦ, НПЦ, пов'язаних із завданнями чи відстежуваних, а також НПЦ, з якими можна взаємодіяти.",
    ["Hostile and Quest NPCs: Display names for hostile NPC's and those NPCs involved with quests or being tracked."] =
        "Ворожі та квестові НПЦ: показувати імена ворожих НПЦ та НПЦ, пов'язаних із завданнями чи відстежуваних.",
    ["Enemy Buffs: Show the temporary beneficial effects applied to the player."] =
        "Підсилення ворогів: показувати тимчасові позитивні ефекти, накладені на гравця.",
    ["Spell Target: Displays the name of the unit being targeted by the spell on the cast bar."] =
        "Ціль закляття: показувати на смузі застосування ім'я цілі закляття.",
    ["Friendly Units: Stack nameplates for friendly units."] =
        "Дружні істоти: складати індикатори імен дружніх істот стосом.",
    ["ALT key: Use the \"ALT\" key to Loot when \"Auto Loot\" is checked, and to Auto Loot when it is not."] =
        "Клавіша ALT: утримуйте ALT для звичайного збору здобичі, коли ввімкнено автозбір, і для автозбору, коли його вимкнено.",
    ["CTRL key: Use the \"CTRL\" key to Loot when \"Auto Loot\" is checked, and to Auto Loot when it is not."] =
        "Клавіша CTRL: утримуйте CTRL для звичайного збору здобичі, коли ввімкнено автозбір, і для автозбору, коли його вимкнено.",
    ["SHIFT key: Use the \"SHIFT\" key to Loot when \"Auto Loot\" is checked, and to Auto Loot when it is not."] =
        "Клавіша SHIFT: утримуйте SHIFT для звичайного збору здобичі, коли ввімкнено автозбір, і для автозбору, коли його вимкнено.",
    ["Personal Debuffs: Show the temporary negative effects you have applied to the player."] =
        "Ваші послаблення: показувати тимчасові негативні ефекти, накладені вами на гравця.",
    ["Personal Debuffs: Show the temporary negative effects you have applied to the unit."] =
        "Ваші послаблення: показувати тимчасові негативні ефекти, накладені вами на істоту.",
    ["Enemy Units: Stack nameplates for enemy units."] =
        "Ворожі істоти: складати індикатори імен ворожих істот стосом.",
    ["Health Value: Displays the unit's current health."] =
        "Значення здоров'я: показувати поточний запас здоров'я істоти.",
    ["Health Percentage: Displays the unit's current health as a percentage of total health."] =
        "Відсоток здоров'я: показувати поточне здоров'я істоти у відсотках від максимального.",
    ["Spell Icon: Displays the icon of the spell on the cast bar."] =
        "Значок закляття: показувати значок закляття на смузі застосування.",
    ["Spell Name: Displays the name of the spell on the cast bar."] =
        "Назва закляття: показувати назву закляття на смузі застосування.",
    ["None: Do not apply a key."] =
        "Немає: не призначати клавішу.",
    ["Big Debuff: Show the temporary crowd control effects you or your allies have applied to the player."] =
        "Сильне послаблення: показувати тимчасові ефекти контролю, накладені вами або вашими союзниками на гравця.",
    ["Health Bar Color: The nameplate health bar will change color if you lose threat on the unit as a tank, or gain threat on a unit as a DPS."] =
        "Колір смуги здоров'я: смуга здоров'я змінюватиме колір, якщо ви втратите загрозу як танк або отримаєте її як боєць.",
    ["Flash When Targeted By Enemy: Controls whether cast bars on nameplates display in a more noticeable way when your character is the target of the spell."] =
        "Блимати, коли ворог бере вас за ціль: робить смуги застосування на індикаторах помітнішими, коли закляття спрямоване на вашого персонажа.",
    ["Flash: The nameplate will flash if you lose threat on the unit as a tank, or gain threat on a unit as a DPS."] =
        "Блимання: індикатор імені блиматиме, якщо ви втратите загрозу як танк або отримаєте її як боєць.",
    ["Mob Buffs: Show the temporary beneficial effects applied to the unit."] =
        "Підсилення істот: показувати тимчасові позитивні ефекти, накладені на істоту.",
    ["Shared CC: Show the temporary crowd control effects you or your allies have applied to the unit."] =
        "Спільний контроль: показувати тимчасові ефекти контролю, накладені вами або вашими союзниками на істоту.",
    ["Highlight Important Casts: Controls whether cast bars on nameplates display in a more noticeable way for important casts."] =
        "Виділяти важливі закляття: робить смуги застосування на індикаторах помітнішими для важливих заклять.",
    ["Progressive: The nameplate will look different if you are close to losing threat on the unit as a tank, or close to gaining threat on a unit as a DPS."] =
        "Поступово: індикатор імені змінюватиметься, коли ви близькі до втрати загрози як танк або до її отримання як боєць.",
    ["Debuff Padding"] = "Відступ послаблень",
    ["Spell Name"] = "Назва закляття",
    ["Spell Icon"] = "Значок закляття",
    ["Highlight Important Casts"] = "Виділяти важливі закляття",
    ["Flash When Targeted By Enemy"] = "Блимати, коли ворог бере вас за ціль",
    ["Ping System"] = "Система сигналів",
    ["Subtitles"] = "Субтитри",
    ["Features"] = "Функції",
    ["Colorblind Mode"] = "Режим корекції кольорів",
    ["Text to Speech"] = "Перетворення тексту на мовлення",
    ["Speech to Text"] = "Перетворення мовлення на текст",

    -- Common controls
    ["Apply"] = "Застосувати",
    ["Okay"] = "Гаразд",
    ["OK"] = "Гаразд",
    ["Cancel"] = "Скасувати",
    ["Close"] = "Закрити",
    ["Defaults"] = "Типові налаштування",
    ["Default"] = "Типове",
    ["Reset"] = "Скинути",
    ["Reset to Default"] = "Скинути до типових",
    ["Enable"] = "Увімкнути",
    ["Disable"] = "Вимкнути",
    ["Enabled"] = "Увімкнено",
    ["Disabled"] = "Вимкнено",
    ["None"] = "Немає",
    ["Not Bound"] = "Не призначено",
    ["SHIFT key"] = "клавіша SHIFT",
    ["Low"] = "Низька",
    ["Fair"] = "Задовільна",
    ["Good"] = "Добра",
    ["High"] = "Висока",
    ["Ultra"] = "Ультра",

    -- Graphics and display
    ["Display"] = "Відображення",
    ["Display Mode"] = "Режим відображення",
    ["Windowed"] = "Віконний",
    ["Windowed (Fullscreen)"] = "Віконний (на весь екран)",
    ["Fullscreen"] = "Повноекранний",
    ["Resolution"] = "Роздільна здатність",
    ["Render Scale"] = "Масштаб рендерингу",
    ["Vertical Sync"] = "Вертикальна синхронізація",
    ["Anti-Aliasing"] = "Згладжування",
    ["Multisample Anti-Aliasing"] = "Багатовибіркове згладжування",
    ["Texture Resolution"] = "Роздільна здатність текстур",
    ["Color 2x / Depth 2x"] = "Колір 2× / глибина 2×",
    ["Texture Filtering"] = "Фільтрація текстур",
    ["Projected Textures"] = "Проєкційні текстури",
    ["View Distance"] = "Дальність огляду",
    ["Environment Detail"] = "Деталізація довкілля",
    ["Ground Clutter"] = "Густота рослинності",
    ["Shadow Quality"] = "Якість тіней",
    ["Liquid Detail"] = "Деталізація рідин",
    ["Particle Density"] = "Щільність частинок",
    ["Depth Effects"] = "Ефекти глибини",
    ["Compute Effects"] = "Обчислювальні ефекти",
    ["Outline Mode"] = "Режим контурів",
    ["Graphics Quality"] = "Якість графіки",
    ["Base Settings"] = "Базові налаштування",
    ["Raid and Battleground"] = "Рейди та поля бою",
    ["Max Foreground FPS"] = "Максимальна частота кадрів на передньому плані",
    ["Max Background FPS"] = "Максимальна фонова частота кадрів",
    ["Target FPS"] = "Цільова частота кадрів",
    ["Resample Quality"] = "Якість масштабування",
    ["Graphics API"] = "Графічний API",
    ["Graphics Card"] = "Відеокарта",
    ["Monitor"] = "Монітор",
    ["Gamma"] = "Гама",
    ["Brightness"] = "Яскравість",
    ["Contrast"] = "Контраст",

    -- Audio
    ["Enable Sound"] = "Увімкнути звук",
    ["Master Volume"] = "Загальна гучність",
    ["Sound Effects"] = "Звукові ефекти",
    ["Music"] = "Музика",
    ["Ambience"] = "Звуки оточення",
    ["Dialog"] = "Діалоги",
    ["Sound in Background"] = "Звук у фоновому режимі",
    ["Error Speech"] = "Озвучення помилок",

    -- Controls, combat, and action bars
    ["Auto Loot"] = "Автоматичний збір здобичі",
    ["Sticky Targeting"] = "Утримання вибраної цілі",
    ["Click-to-Move"] = "Переміщення клацанням",
    ["Mouse Sensitivity"] = "Чутливість миші",
    ["Invert Mouse"] = "Інвертувати мишу",
    ["Enable Mouseover Cast"] = "Застосування заклять наведенням",
    ["Auto Dismount in Flight"] = "Автоматично спішуватися в польоті",
    ["Enable Interact Key"] = "Увімкнути клавішу взаємодії",
    ["Interact Key"] = "Клавіша взаємодії",
    ["Floating Combat Text"] = "Плавучий бойовий текст",
    ["Attack on Assist"] = "Атакувати під час допомоги",
    ["Stop Auto Attack"] = "Зупиняти автоатаку",
    ["Target of Target"] = "Ціль цілі",
    ["Loss of Control Alerts"] = "Сповіщення про втрату контролю",
    ["Spell Alert Opacity"] = "Прозорість сповіщень про закляття",
    ["Lock Action Bars"] = "Заблокувати панелі дій",
    ["Always Show Action Bars"] = "Завжди показувати панелі дій",
    ["Show Numbers for Cooldowns"] = "Показувати числа часу відновлення",
    ["Bottom Left Bar"] = "Нижня ліва панель",
    ["Bottom Right Bar"] = "Нижня права панель",
    ["Right Bar"] = "Права панель",
    ["Right Bar 2"] = "Права панель 2",

    -- Names and interface
    ["My Name"] = "Моє ім'я",
    ["Friendly Players"] = "Дружні гравці",
    ["Enemy Players"] = "Ворожі гравці",
    ["Friendly Units"] = "Дружні істоти",
    ["Enemy Units"] = "Ворожі істоти",
    ["Minions"] = "Прислужники",
    ["Totems"] = "Тотеми",
    ["Unit Nameplates"] = "Індикатори істот",
    ["Friendly NPC Nameplates"] = "Індикатори імен дружніх NPC",
    ["Only Show Names"] = "Показувати лише імена",
    ["Realm Name"] = "Назва світу",
    ["Show Offscreen Nameplates"] = "Показувати індикатори імен поза екраном",
    ["Stack Nameplates"] = "Складати індикатори імен",
    ["Use Class Color for Names"] = "Використовувати колір класу для імен",
    ["Larger Nameplates"] = "Збільшені індикатори",
    ["Personal Resource Display"] = "Особистий індикатор ресурсів",
    ["Status Text"] = "Текст стану",
    ["Display Lua Errors"] = "Показувати помилки Lua",
    ["Show Tutorials"] = "Показувати навчальні підказки",
    ["Reset Tutorials"] = "Скинути навчання",
    ["Chat Bubbles"] = "Бульбашки чату",
    ["Party Chat Bubbles"] = "Бульбашки групового чату",
    ["Raid Chat Bubbles"] = "Бульбашки рейдового чату",
    ["Replace Player Frame Portraits"] = "Замінити портрети рамок гравців",
    ["Replace My Frame Portrait"] = "Замінити портрет моєї рамки",
    ["Show Low-Level Quests"] = "Показувати низькорівневі завдання",
    ["Toasts"] = "Сповіщення",
    ["Show Item Toasts"] = "Показувати сповіщення про предмети",
    ["Show Collection Toasts"] = "Показувати сповіщення про колекції",
    ["Show Recipe Toasts"] = "Показувати сповіщення про рецепти",
    ["Open Loot Window at Mouse"] = "Відкривати вікно здобичі біля курсора",
    ["Mouse Look Speed"] = "Швидкість огляду мишею",
    ["Auto Loot Key"] = "Клавіша автоматичного збору",
    ["Lock Cursor to Window"] = "Обмежити курсор вікном",
    ["Combine Bags"] = "Об'єднати сумки",
    ["Interact On Left Click"] = "Взаємодія лівою кнопкою миші",
    ["Auto Cancel Away Mode"] = "Автоматично скасовувати стан «Відійшов»",
    ["Interact With Target"] = "Взаємодія з ціллю",
    ["Interact Key Sound Cue"] = "Звуковий сигнал клавіші взаємодії",
    ["Enable Mouse Sensitivity"] = "Увімкнути чутливість миші",
    ["FidelityFX Super Resolution 1.0: AMD FidelityFX Super Resolution 1.0 is a cutting edge super-optimized spatial upscaling technology that produces impressive image quality at fast framerates."] = "FidelityFX Super Resolution 1.0: AMD FidelityFX Super Resolution 1.0 — передова, надзвичайно оптимізована технологія просторового масштабування, що забезпечує вражаючу якість зображення за високої частоти кадрів.",
    ["Good: Ray Traced Shadows from directional and local light sources at reduced resolution."] = "Добре: тіні з трасуванням променів від спрямованих і локальних джерел світла зі зниженою роздільною здатністю.",
    ["High: Ray Traced Shadows from directional and local light sources at full resolution."] = "Високо: тіні з трасуванням променів від спрямованих і локальних джерел світла з повною роздільною здатністю.",
    ["Triple buffering evens out frame rate spikes but may slightly increase input latency on slower GPUs. Enabled: Triple Buffering Disabled: Double Buffering"] = "Потрійна буферизація згладжує стрибки частоти кадрів, але може дещо збільшити затримку введення на повільніших графічних процесорах. Увімкнено: потрійна буферизація. Вимкнено: подвійна буферизація.",
    ["Fair: Ray Traced Shadows from directional light sources at reduced resolution."] = "Задовільно: тіні з трасуванням променів від спрямованих джерел світла зі зниженою роздільною здатністю.",
    ["Aggressive: Minor loss to fine detail"] = "Агресивно: незначна втрата дрібних деталей",
    ["Bicubic: An upscale resulting in a soft image or improved quality SSAA if above 100% render scale."] = "Бікубічне: масштабування створює м'яке зображення або покращує якість SSAA, якщо масштаб рендерингу перевищує 100%.",
    ["Point: An upscale resulting in a hard, pixelated image."] = "Точкове: масштабування створює різке, пікселізоване зображення.",
    ["Bilinear: An upscale resulting in a very soft image or standard quality SSAA if above 100% render scale."] = "Білінійне: масштабування створює дуже м'яке зображення або стандартну якість SSAA, якщо масштаб рендерингу перевищує 100%.",
    ["Auto Detect: Selected Graphics API. Auto-detect best available Graphics API."] = "Автовизначення: вибраний графічний API. Автоматично визначає найкращий доступний графічний API.",
    ["Standard: Almost no loss to visual quality"] = "Стандартно: майже без втрати якості зображення",
    ["DirectX 12: Current Graphics API."] = "DirectX 12: поточний графічний API.",
}

if addonTable.forever_catalog then
    addonTable.forever_catalog.register_ui_source(
        "settings", "curated", settings, 200)
else
    addonTable.forever_ui = addonTable.forever_ui or {}
    for english, ukrainian in pairs(settings) do
        if addonTable.forever_ui[english] == nil then
            addonTable.forever_ui[english] = ukrainian
        end
    end
end

-- Same English label can mean different things in different parts of the UI.
addonTable.forever_ui_context = {
    { text = "Send Mail", frame = "MailFrameTab2.Text", translation = "Надіслати" },
    { text = "Custom", frame = "LFGListingFrameCategoryView", translation = "Користувацькі групи" },
    { text = "Back", frame = "Quest", translation = "Назад" },
    { text = "Common", frame = "LootFrame", translation = "Звичайний" },
    { text = "Common", frame = "LootButton", translation = "Звичайний" },
    { text = "General", frame = "ChatFrame", translation = "Загальний" },
    { text = "General", frame = "CharacterStatsPane", translation = "Загальне" },
    { text = "General", frame = "Settings", translation = "Загальні" },
    { text = "invites you to join the guild:", frame = "GuildInviteFrameInviteText", translation = "запрошує вас до гільдії:" },
    { text = "Join Guild", frame = "GuildInviteFrameJoinButton", translation = "Вступити" },
    { text = "Decline Invitation", frame = "GuildInviteFrameDeclineButton", translation = "Відхилити" },
}
