local _, addon_table = ...

-- User-supplied faction translations matched by ID to the active client inventory.
local database = {
    sourceBuild = "1.60.1.70338",
    count = 253,
    rows = {
        [1] = { en = "PLAYER, Human", name = "ГРАВЕЦЬ, людина", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2] = { en = "PLAYER, Orc", name = "ГРАВЕЦЬ, орк", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [3] = { en = "PLAYER, Dwarf", name = "ГРАВЕЦЬ, дворф", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [4] = { en = "PLAYER, Night Elf", name = "ГРАВЕЦЬ, нічний ельф", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [5] = { en = "PLAYER, Undead", name = "ГРАВЕЦЬ, невмерлий", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [6] = { en = "PLAYER, Tauren ", name = "ГРАВЕЦЬ, таурен", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [7] = { en = "Creature", name = "Істота", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [8] = { en = "PLAYER, Gnome", name = "ГРАВЕЦЬ, гном", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [9] = { en = "PLAYER, Troll", name = "ГРАВЕЦЬ, троль", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [14] = { en = "Monster", name = "Монстр", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [15] = { en = "Defias Brotherhood", name = "Братство Непокірних", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [16] = { en = "Gnoll - Riverpaw", name = "Ґнол — Річкова Лапа", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [17] = { en = "Gnoll - Redridge", name = "Ґнол — Багряногір'я", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [18] = { en = "Gnoll - Shadowhide", name = "Ґнол — Тінешкурі", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [19] = { en = "Murloc", name = "Мурлок", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [20] = { en = "Undead, Scourge", name = "Невмерлі, Скара", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [21] = { en = "Booty Bay", name = "Бухта Наживи", en_description = "This booming coastal city is run by Baron Revilgaz of the Blackwater Raiders.  Mortal enemies of the Bloodsail Buccaneers and part of the Steamwheedle Cartel.", description = "Цим квітучим прибережним містом керує барон Ревілґаз із Рейдерів Чорноводдя. Їхні смертельні вороги — Буканьєри Кривавого Вітрила, а самі вони входять до Картелю Паровиманів.", parent = 169, reputation_index = 1, flags = 0 },
        [22] = { en = "Beast - Spider", name = "Звір — павук", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [23] = { en = "Beast - Boar", name = "Звір — вепр", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [24] = { en = "Worgen", name = "Ворґен", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [25] = { en = "Kobold", name = "Кобольд", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [26] = { en = "Troll, Bloodscalp", name = "Троль, Кривавий Скальп", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [27] = { en = "Troll, Skullsplitter", name = "Троль, Череполом", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [28] = { en = "Prey", name = "Здобич", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [29] = { en = "Beast - Wolf", name = "Звір — вовк", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [30] = { en = "Defias Brotherhood Traitor", name = "Зрадник Братства Непокірних", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [31] = { en = "Friendly", name = "Дружній", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [32] = { en = "Trogg", name = "Троґґ", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [33] = { en = "Troll, Frostmane", name = "Троль, Морозна Грива", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [34] = { en = "Orc, Blackrock", name = "Орк, Чорний Камінь", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [35] = { en = "Villain", name = "Лиходій", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [36] = { en = "Victim", name = "Жертва", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [37] = { en = "Beast - Bear", name = "Звір — ведмідь", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [38] = { en = "Ogre", name = "Огр", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [39] = { en = "Kurzen's Mercenaries", name = "Найманці Курцена", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [40] = { en = "Escortee", name = "Супроводжуваний", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [41] = { en = "Venture Company", name = "Компанія «Авантюра»", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [42] = { en = "Beast - Raptor", name = "Звір — раптор", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [43] = { en = "Basilisk", name = "Василіск", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [44] = { en = "Dragonflight, Green", name = "Драконяча зграя, зелена", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [45] = { en = "Lost Ones", name = "Заблудлі", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [46] = { en = "Blacksmithing - Armorsmithing", name = "Ковальство — бронярство", en_description = "", description = "", parent = 0, reputation_index = 29, flags = 0 },
        [47] = { en = "Ironforge", name = "Залізогарт", en_description = "This Alliance capital is the pride of the Dun Morogh dwarves.  Home to King Magni.", description = "Ця столиця Альянсу — гордість дворфів Дун-Морогу. Тут править король Маґні.", parent = 469, reputation_index = 20, flags = 0 },
        [48] = { en = "Dark Iron Dwarves", name = "Дворфи Темного Заліза", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [49] = { en = "Human, Night Watch", name = "Людина, Нічна варта", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [50] = { en = "Dragonflight, Red", name = "Драконяча зграя, червона", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [51] = { en = "Gnoll - Mosshide", name = "Ґнол — Мохошкурі", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [52] = { en = "Orc, Dragonmaw", name = "Орк, Драконова Паща", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [53] = { en = "Gnome - Leper", name = "Гном — прокажений", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [54] = { en = "Gnomeregan Exiles", name = "Вигнанці Ґномреґана", en_description = "The former denizens of Gnomeregan, now living in exile in Ironforge and in league with the Alliance.", description = "Колишні мешканці Ґномреґана, що нині живуть у вигнанні в Залізогарті та перебувають у союзі з Альянсом.", parent = 469, reputation_index = 18, flags = 0 },
        [55] = { en = "Leopard", name = "Леопард", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [56] = { en = "Scarlet Crusade", name = "Багряний Похід", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [57] = { en = "Gnoll - Rothide", name = "Ґнол — Гнилошкурі", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [58] = { en = "Beast - Gorilla", name = "Звір — горила", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [59] = { en = "Thorium Brotherhood", name = "Торієве Братство", en_description = "The dwarves of the Thorium Brotherhood epitomize excellence in craftsmanship and are bent on unlocking the secrets of Blackrock Mountain.", description = "Дворфи Торієвого Братства уособлюють вершину ремісничої майстерності й прагнуть розкрити таємниці Чорнокамінної гори.", parent = 0, reputation_index = 4, flags = 0 },
        [60] = { en = "Naga", name = "Наґа", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [61] = { en = "Dalaran", name = "Даларан", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [62] = { en = "Forlorn Spirit", name = "Покинутий дух", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [63] = { en = "Darkhowl", name = "Темновий", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [64] = { en = "Grell", name = "Ґрелль", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [65] = { en = "Furbolg", name = "Фурболґ", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [66] = { en = "Horde Generic", name = "Орда — загальна", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [67] = { en = "Horde", name = "Орда", en_description = "", description = "", parent = 0, reputation_index = 12, flags = 0 },
        [68] = { en = "Undercity", name = "Підмісто", en_description = "Led by Sylvanas Windrunner, the Forsaken have joined a tenuous alliance with the Horde and established this capital in the vast depths under the Ruins of Lordaeron.", description = "Під проводом Сільвани Вітрогін Відречені уклали хиткий союз з Ордою та заснували цю столицю в безмежних глибинах під руїнами Лордерону.", parent = 67, reputation_index = 17, flags = 0 },
        [69] = { en = "Darnassus", name = "Дарнас", en_description = "The Alliance capital is populated by Night Elves and is located in the island of Teldrassil.  Ruled by the Priestess of the Moon, Tyrande Whisperwind.", description = "Цю столицю Альянсу, розташовану на острові Тельдрассіль, населяють нічні ельфи. Нею править жриця Місяця Тіранда Шелест Вітру.", parent = 469, reputation_index = 21, flags = 0 },
        [70] = { en = "Syndicate", name = "Синдикат", en_description = "A primarily human criminal organization that operates mostly out of the Alterac Mountains and Hillsbrad Foothills.", description = "Переважно людська злочинна організація, що діє здебільшого в Альтерацьких горах і Гіллзбрадському передгір'ї.", parent = 0, reputation_index = 6, flags = 0 },
        [71] = { en = "Hillsbrad Militia", name = "Гіллзбрадське ополчення", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [72] = { en = "Stormwind", name = "Штормовій", en_description = "One of the last bastions of human power, this Alliance capital is ruled by the child king, Anduin Wrynn.", description = "Один з останніх бастіонів людської могутності. Цією столицею Альянсу править юний король Андуїн Рінн.", parent = 469, reputation_index = 19, flags = 0 },
        [73] = { en = "Demon", name = "Демон", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [74] = { en = "Elemental", name = "Стихії", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [75] = { en = "Spirit", name = "Дух", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [76] = { en = "Orgrimmar", name = "Орґріммар", en_description = "Founded by Thrall, this Horde capital city is home to many of the proud orc clans of Durotar.", description = "Заснований Траллом, Орґріммар є столицею Орди та домівкою для багатьох гордих орчих кланів Дуротару.", parent = 67, reputation_index = 14, flags = 0 },
        [77] = { en = "Treasure", name = "Скарб", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [78] = { en = "Gnoll - Mudsnout", name = "Ґнол — Брудне Рило", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [79] = { en = "HIllsbrad, Southshore Mayor", name = "Гіллзбрад, мер Південнобережжя", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [80] = { en = "Dragonflight, Black", name = "Драконяча зграя, чорна", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [81] = { en = "Thunder Bluff", name = "Громовий Бескид", en_description = "Cairne Bloodhoof leads his people, the Proud Tauren, from this mighty Horde capital.", description = "Керн Криваве Копито веде свій народ, гордих тауренів, із цієї могутньої столиці Орди.", parent = 67, reputation_index = 16, flags = 0 },
        [82] = { en = "Troll, Witherbark", name = "Троль, Сухокорі", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [83] = { en = "Leatherworking - Elemental", name = "Шкірництво — стихійне", en_description = "", description = "", parent = 0, reputation_index = 23, flags = 0 },
        [84] = { en = "Quilboar, Razormane", name = "Свинобраз, Гострогриві", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [85] = { en = "Quilboar, Bristleback", name = "Свинобраз, Щетиноспини", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [86] = { en = "Leatherworking - Dragonscale", name = "Шкірництво — драконяча луска", en_description = "", description = "", parent = 0, reputation_index = 22, flags = 0 },
        [87] = { en = "Bloodsail Buccaneers", name = "Буканьєри Кривавого Вітрила", en_description = "These bloodthirsty corsairs are the bane of many a merchant in the high seas.  Sworn enemies of Booty Bay.", description = "Ці кровожерливі корсари — справжня погибель для багатьох торговців у відкритому морі. Закляті вороги Бухти Наживи.", parent = 0, reputation_index = 0, flags = 0 },
        [88] = { en = "Blackfathom", name = "Чорноводдя", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [89] = { en = "Makrura", name = "Макрура", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [90] = { en = "Centaur, Kolkar", name = "Кентавр, Колкар", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [91] = { en = "Centaur, Galak", name = "Кентавр, Ґалак", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [92] = { en = "Gelkis Clan Centaur", name = "Кентаври клану Ґелкіс", en_description = "These centaur have made their home in the southern region of Desolace.  Mortal enemies of the Magram Centaur.", description = "Ці кентаври оселилися в південній частині Спустошища. Смертельні вороги кентаврів Маґрам.", parent = 0, reputation_index = 2, flags = 0 },
        [93] = { en = "Magram Clan Centaur", name = "Кентаври клану Маґрам", en_description = "These centaur have made their home in the eastern region of Desolace.  Mortal enemies of the Gelkis Centaur.", description = "Ці кентаври оселилися у східній частині Спустошища. Смертельні вороги кентаврів Ґелкіс.", parent = 0, reputation_index = 3, flags = 0 },
        [94] = { en = "Maraudine", name = "Мародіни", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [108] = { en = "Theramore", name = "Терамор", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [109] = { en = "Quilboar, Razorfen", name = "Свинобраз, Голкоболотні", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [110] = { en = "Quilboar, Razormane 2", name = "Свинобраз, Гострогриві 2", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [111] = { en = "Quilboar, Deathshead", name = "Свинобраз, Мертва Голова", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [128] = { en = "Enemy", name = "Ворог", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [148] = { en = "Ambient", name = "Оточення", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [168] = { en = "Nethergarde Caravan", name = "Караван Підсвітньої Варти", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [169] = { en = "Steamwheedle Cartel", name = "Картель Паровиманів", en_description = "", description = "", parent = 0, reputation_index = 10, flags = 0 },
        [189] = { en = "Alliance Generic", name = "Альянс — загальна", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [209] = { en = "Nethergarde", name = "Підсвітня Варта", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [229] = { en = "Wailing Caverns", name = "Плачучі печери", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [249] = { en = "Silithid", name = "Силітид", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [269] = { en = "Silvermoon Remnant", name = "Залишки Срібномісяця", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [270] = { en = "Zandalar Tribe", name = "Плем'я Зандалар", en_description = "These trolls have come to Yojamba Isle in an effort to recruit help against the resurrected Blood God and his Atal'ai Priests in Zul'Gurub.", description = "Ці тролі прибули на острів Йоджамба, щоб знайти союзників у боротьбі проти воскреслого Бога Крові та його жерців Атал'ай у Зул'Ґурубі.", parent = 0, reputation_index = 51, flags = 0 },
        [289] = { en = "Blacksmithing - Weaponsmithing", name = "Ковальство — зброярство", en_description = "", description = "", parent = 0, reputation_index = 30, flags = 0 },
        [309] = { en = "Scorpid", name = "Скорпід", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [310] = { en = "Beast - Bat", name = "Звір — кажан", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [311] = { en = "Titan", name = "Титан", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [329] = { en = "Taskmaster Fizzule", name = "Наглядач Фіззул", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [349] = { en = "Ravenholdt", name = "Воронячий Пагорб", en_description = "This guild of thieves and assassins welcomes only those of extraordinary prowess into its fold.  Sworn rivals of the Syndicate.", description = "Ця гільдія злодіїв і вбивць приймає до своїх лав лише тих, хто довів виняткову майстерність. Закляті суперники Синдикату.", parent = 0, reputation_index = 5, flags = 0 },
        [369] = { en = "Gadgetzan", name = "Штуковинськ", en_description = "Capital of the Steamwheedle Cartel and home to goblinhood's finest engineers, alchemists and merchants.", description = "Столиця Картелю Паровиманів і осередок найкращих гоблінських інженерів, алхіміків та торговців.", parent = 169, reputation_index = 7, flags = 0 },
        [389] = { en = "Gnomeregan Bug", name = "Жук Ґномреґана", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [409] = { en = "Harpy", name = "Гарпія", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [429] = { en = "Burning Blade", name = "Палаючий Клинок", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [449] = { en = "Shadowsilk Poacher", name = "Браконьєр Тіньового Шовку", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [450] = { en = "Searing Spider", name = "Пекучий павук", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [469] = { en = "Alliance", name = "Альянс", en_description = "", description = "", parent = 0, reputation_index = 11, flags = 0 },
        [470] = { en = "Ratchet", name = "Брашпиль", en_description = "Part of the Steamwheedle Cartel, this goblin city provides a neutral haven for those that wish to trade goods and services in the Barrens.", description = "Частина Картелю Паровиманів, це гоблінське місто є нейтральним прихистком для тих, хто бажає торгувати товарами й послугами в Степах.", parent = 169, reputation_index = 9, flags = 0 },
        [471] = { en = "Wildhammer Clan", name = "Клан Диких Молотів", en_description = "Though not a part of the Alliance, the dwarves of Aerie Peak have opened their doors to it and hold the Horde as enemies.", description = "Хоча дворфи Диких Молотів з Орлиного Піку не входять до Альянсу, вони відчинили перед ним свої брами й вважають Орду ворогом.", parent = 0, reputation_index = 8, flags = 0 },
        [489] = { en = "Goblin, Dark Iron Bar Patron", name = "Гоблін, відвідувач таверни Темного Заліза", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [509] = { en = "The League of Arathor", name = "Ліга Аратора", en_description = "The League of Arathor seeks to reclaim lost land of Arathi Basin for their benefactors in Stormwind.", description = "Ліга Аратора прагне повернути втрачені землі Низини Араті для своїх покровителів зі Штормовію.", parent = 891, reputation_index = 53, flags = 0 },
        [510] = { en = "The Defilers", name = "Осквернителі", en_description = "The Defilers seek to claim Arathi Basin's valuable resources for the Horde.", description = "Осквернителі прагнуть заволодіти цінними ресурсами Низини Араті для Орди.", parent = 892, reputation_index = 52, flags = 0 },
        [511] = { en = "Giant", name = "Велетень", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [529] = { en = "Argent Dawn", name = "Сріблястий Світанок", en_description = "An organization focused on protecting Azeroth from the threat of the Scourge.  Strongholds of the Argent Dawn can be found in the Eastern and Western Plaguelands.", description = "Організація, що зосередилася на захисті Азероту від загрози Скари. Опорні пункти Сріблястого Світанку можна знайти у Східному та Західному Чумнозем'ї.", parent = 0, reputation_index = 13, flags = 0 },
        [530] = { en = "Darkspear Trolls", name = "Тролі Темного Списа", en_description = "This tribe of exiled trolls has joined forces with Thrall and the Horde.  They now call Durotar their home, which they share with their orc allies.", description = "Це плем'я вигнаних тролів об'єдналося з Траллом та Ордою. Тепер вони називають Дуротар своїм домом і ділять його зі своїми союзниками-орками.", parent = 67, reputation_index = 15, flags = 0 },
        [531] = { en = "Dragonflight, Bronze", name = "Драконяча зграя, бронзова", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [532] = { en = "Dragonflight, Blue", name = "Драконяча зграя, синя", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [549] = { en = "Leatherworking - Tribal", name = "Шкірництво — племінне", en_description = "", description = "", parent = 0, reputation_index = 24, flags = 0 },
        [550] = { en = "Engineering - Goblin", name = "Інженерія — гоблінська", en_description = "", description = "", parent = 0, reputation_index = 26, flags = 0 },
        [551] = { en = "Engineering - Gnome", name = "Інженерія — гномська", en_description = "", description = "", parent = 0, reputation_index = 25, flags = 0 },
        [569] = { en = "Blacksmithing - Hammersmithing", name = "Ковальство — молотобійство", en_description = "", description = "", parent = 0, reputation_index = 33, flags = 0 },
        [570] = { en = "Blacksmithing - Axesmithing", name = "Ковальство — сокирництво", en_description = "", description = "", parent = 0, reputation_index = 31, flags = 0 },
        [571] = { en = "Blacksmithing - Swordsmithing", name = "Ковальство — мечництво", en_description = "", description = "", parent = 0, reputation_index = 32, flags = 0 },
        [572] = { en = "Troll, Vilebranch", name = "Троль, Лихогілля", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [573] = { en = "Southsea Freebooters", name = "Флібустьєри Південних морів", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [574] = { en = "Caer Darrow", name = "Каєр-Дерроу", en_description = "", description = "", parent = 0, reputation_index = 34, flags = 0 },
        [575] = { en = "Furbolg, Uncorrupted", name = "Фурболґ, неосквернений", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [576] = { en = "Timbermaw Hold", name = "Оплот Деревопузих", en_description = "As one of the last uncorrupted furbolg tribes, the Timbermaw seek to preserve their spiritual ways and end the suffering of their brethren.", description = "Як одне з останніх неосквернених племен фурболґів, Деревопащі прагнуть зберегти свої духовні традиції та покласти край стражданням своїх родичів.", parent = 0, reputation_index = 35, flags = 0 },
        [577] = { en = "Everlook", name = "Завшегляд", en_description = "This trading post is run by the goblins of the Steamwheedle Cartel and it sits in the crossroads of Winterspring's main trade routes.", description = "Цей торговельний пост утримують гобліни Картелю Паровиманів. Він стоїть на перехресті головних торговельних шляхів Зимоключа.", parent = 169, reputation_index = 28, flags = 0 },
        [589] = { en = "Wintersaber Trainers", name = "Дресирувальники зимових шаблезубів", en_description = "This small group of reclusive night elves raises and trains wintersabers in the Winterspring area.", description = "Ця невелика група відлюдькуватих нічних ельфів вирощує та дресирує зимових шаблезубів у Зимоключі.", parent = 0, reputation_index = 27, flags = 0 },
        [609] = { en = "Cenarion Circle", name = "Кенарієве Коло", en_description = "The druids of Cenarion Circle are guardians of nature and make their home in tranquil Moonglade.", description = "Друїди Кенарієвого Кола — хранителі природи, що оселилися в тихому Місячному Гаю.", parent = 0, reputation_index = 36, flags = 0 },
        [629] = { en = "Shatterspear Trolls", name = "Тролі Розбитого Списа", en_description = "", description = "", parent = 0, reputation_index = 37, flags = 0 },
        [630] = { en = "Ravasaur Trainers", name = "Дресирувальники равазаврів", en_description = "The ravasaurs of Un'Goro Crater are incredibly deadly, but a few individuals have learned how to tame them.", description = "Равазаври кратера Ун'Ґоро неймовірно смертоносні, але кільком сміливцям вдалося навчитися їх приручати.", parent = 0, reputation_index = 38, flags = 0 },
        [649] = { en = "Majordomo Executus", name = "Мажордом Екзекутус", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [669] = { en = "Beast - Carrion Bird", name = "Звір — падальник", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [670] = { en = "Beast - Cat", name = "Звір — кіт", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [671] = { en = "Beast - Crab", name = "Звір — краб", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [672] = { en = "Beast - Crocilisk", name = "Звір — кроколіск", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [673] = { en = "Beast - Hyena", name = "Звір — гієна", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [674] = { en = "Beast - Owl", name = "Звір — сова", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [675] = { en = "Beast - Scorpid", name = "Звір — скорпід", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [676] = { en = "Beast - Tallstrider", name = "Звір — довгоніг", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [677] = { en = "Beast - Turtle", name = "Звір — черепаха", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [678] = { en = "Beast - Wind Serpent", name = "Звір — вітряний змій", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [679] = { en = "Training Dummy", name = "Тренувальний манекен", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [689] = { en = "Dragonflight, Black - Bait", name = "Драконяча зграя, чорна — приманка", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [709] = { en = "Battleground Neutral", name = "Поле бою — нейтральна", en_description = "", description = "", parent = 0, reputation_index = 39, flags = 0 },
        [729] = { en = "Frostwolf Clan", name = "Клан Морозних Вовків", en_description = "The Frostwolf Clan seeks to drive out the dwarves of the Stormpike Expedition from Alterac Valley.", description = "Клан Морозних Вовків прагне вигнати дворфів Експедиції Грозової Вершини з Альтерацької долини.", parent = 892, reputation_index = 41, flags = 0 },
        [730] = { en = "Stormpike Guard", name = "Варта Грозової Вершини", en_description = "The Stormpike Dwarves have set up residence in Alterac Valley, where they're locked in battle with the Frostwolf Orcs.", description = "Дворфи Грозової Вершини оселилися в Альтерацькій долині, де ведуть безперервну боротьбу з орками Морозних Вовків.", parent = 891, reputation_index = 40, flags = 0 },
        [749] = { en = "Hydraxian Waterlords", name = "Гідраксійські Володарі Води", en_description = "These elementals have made their home on the islands east of Azshara.  Sworn enemies of the armies of Ragnaros.", description = "Ці елементалі оселилися на островах на схід від Азшари. Закляті вороги армій Раґнароса.", parent = 0, reputation_index = 42, flags = 0 },
        [750] = { en = "Sulfuron Firelords", name = "Володарі вогню Сульфурона", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [769] = { en = "Gizlock's Dummy", name = "Манекен Ґізлока", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [770] = { en = "Gizlock's Charm", name = "Чари Ґізлока", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [771] = { en = "Gizlock", name = "Ґізлок", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [789] = { en = "Moro'gai", name = "Моро'ґай", en_description = "", description = "", parent = 0, reputation_index = 43, flags = 0 },
        [790] = { en = "Spirit Guide - Alliance", name = "Дух-провідник — Альянс", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [809] = { en = "Shen'dralar", name = "Шен'дралар", en_description = "A remnant of the once powerful elves living in Dire Maul, yet still wise and knowledgeable about great secrets.", description = "Залишки колись могутніх ельфів, що живуть у Страхомісті; вони й досі зберігають мудрість і знання великих таємниць.", parent = 0, reputation_index = 44, flags = 0 },
        [829] = { en = "Ogre (Captain Kromcrush)", name = "Огр (капітан Кромкраш)", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [849] = { en = "Spirit Guide - Horde", name = "Дух-провідник — Орда", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [869] = { en = "Jaedenar", name = "Джеденар", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [889] = { en = "Warsong Outriders", name = "Вершники Пісні Війни", en_description = "Fierce orcs of the Warsong Clan, locked in battle against the Silverwing Sentinels in Warsong Gulch.", description = "Люті орки клану Пісні Війни, що ведуть запеклу боротьбу з Вартовими Срібного Крила в Ущелині Пісні Війни.", parent = 892, reputation_index = 46, flags = 0 },
        [890] = { en = "Silverwing Sentinels", name = "Вартові Срібного Крила", en_description = "Staunch defenders of Ashenvale, locked in battle against the Warsong Outriders in Warsong Gulch.", description = "Непохитні захисники Ясенедолу, що ведуть боротьбу з Вершниками Пісні Війни в Ущелині Пісні Війни.", parent = 891, reputation_index = 45, flags = 0 },
        [891] = { en = "Alliance Forces", name = "Сили Альянсу", en_description = "", description = "", parent = 0, reputation_index = 47, flags = 0 },
        [892] = { en = "Horde Forces", name = "Сили Орди", en_description = "", description = "", parent = 0, reputation_index = 48, flags = 0 },
        [893] = { en = "Revantusk Trolls", name = "Тролі Зловісного Ікла", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [909] = { en = "Darkmoon Faire", name = "Ярмарок Темного Місяця", en_description = "A traveling fair that showcases the weird and the extraordinary.  Often spotted in Elwynn Forest and Mulgore.", description = "Мандрівний ярмарок, де можна побачити дивовижне й незвичайне. Його часто можна зустріти в Ельвиннському лісі та Мулґорі.", parent = 0, reputation_index = 50, flags = 0 },
        [910] = { en = "Brood of Nozdormu", name = "Нащадки Ноздорму", en_description = "The descendants of the Bronze Dragonflight are the guardians of time and care little for the mortal races.", description = "Нащадки Бронзової драконячої зграї — хранителі часу, яким мало діла до смертних рас.", parent = 0, reputation_index = 54, flags = 0 },
        [912] = { en = "Might of Kalimdor", name = "Міць Калімдору", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [915] = { en = "Armies of C'Thun", name = "Армії К'Туна", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [916] = { en = "Silithid Attackers", name = "Нападники-силітиди", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [917] = { en = "The Ironforge Brigade", name = "Бригада Залізогарту", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [918] = { en = "RC Enemies", name = "RC — вороги", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [919] = { en = "RC Objects", name = "RC — об'єкти", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [920] = { en = "Red", name = "Червоні", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [921] = { en = "Blue", name = "Сині", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [928] = { en = "Scourge Invaders", name = "Загарбники Скари", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [931] = { en = "Test Faction (not a real faction)", name = "Тестова фракція (не справжня фракція)", en_description = "This faction only exists to test the editing of faction names and descriptions...", description = "Ця фракція існує лише для перевірки редагування назв і описів фракцій...", parent = 0, reputation_index = -1, flags = 0 },
        [950] = { en = "ToWoW - Flag", name = "ToWoW — прапор", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [951] = { en = "ToWoW - Flag Trigger Alliance (DND)", name = "ToWoW — спрацювання прапора Альянсу (DND)", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [954] = { en = "ToWoW - Flag Trigger Horde (DND)", name = "ToWoW — спрацювання прапора Орди (DND)", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [1041] = { en = "Frenzy", name = "Шаленство", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2402] = { en = "CTF - Flag - Horde", name = "CTF — прапор — Орда", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2403] = { en = "CTF - Flag - Alliance", name = "CTF — прапор — Альянс", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2505] = { en = "Dragonflight, Chromatic", name = "Драконяча зграя, хроматична", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2586] = { en = "Azeroth Commerce Authority", name = "Управління торгівлі Азероту", en_description = "Originally commissioned to facilitate trade across the Eastern Kingdoms, the ACA now maintains supply routes to Alliance forces worldwide.", description = "Спочатку Управління торгівлі Азероту було створене для сприяння торгівлі між Східними Королівствами, а нині воно підтримує шляхи постачання сил Альянсу по всьому світу.", parent = 0, reputation_index = 49, flags = 0 },
        [2587] = { en = "Durotar Supply and Logistics", name = "Постачання й логістика Дуротару", en_description = "The Horde's robust supply network fuels its rapid expansion across Kalimdor and beyond.", description = "Розгалужена мережа постачання Орди забезпечує її стрімке розширення Калімдором і за його межами.", parent = 0, reputation_index = 55, flags = 0 },
        [2588] = { en = "S03 - Scarlet Crusade Disguise", name = "S03 — маскування під Багряний Похід", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2634] = { en = "Blood Moon", name = "Кривавий місяць", en_description = "The skies are red, and your senses are overpowered with the thirst for blood!", description = "Небо червоніє, а твої чуття поглинає жага крові!", parent = 0, reputation_index = -1, flags = 0 },
        [2641] = { en = "Emerald Wardens", name = "Смарагдові вартові", en_description = "A hastily-organized group of Druids, working with both the Alliance and the Horde to stop the Nightmare Incursions.", description = "Поспіхом організована група друїдів, яка співпрацює і з Альянсом, і з Ордою, щоб зупинити вторгнення Кошмару.", parent = 0, reputation_index = 56, flags = 0 },
        [2646] = { en = "S03 - 50 - Tanaris Arena Opponent", name = "S03 — 50 — суперник арени Танаріса", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2650] = { en = "S03 - 60 - Western Plaguelands - Mage Runecarving", name = "S03 — 60 — Західне Чумнозем'я — рунорізьблення мага", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2660] = { en = "Elemental (The Molten Core Adds)", name = "Елементаль (додаткові істоти Вогняних Надр)", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2661] = { en = "Hydraxian (The Molten Core Adds)", name = "Гідраксійці (додаткові істоти Вогняних Надр)", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2679] = { en = "Order of the Silver Hand", name = "Орден Срібної Десниці", en_description = "A monastic order of holy warriors sworn to the service of the king of Lordaeron.", description = "Чернечий орден святих воїнів, які присягнули служити королю Лордерону.", parent = 469, reputation_index = -1, flags = 0 },
        [2686] = { en = "S03 - Scourge Disguise", name = "S03 — маскування під Скару", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2687] = { en = "Hunter Quest Boss (Tamed Beast)", name = "Бос завдання мисливця (приручений звір)", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2719] = { en = "Cenarion Scouts", name = "Кенарійські розвідники", en_description = "The Cenarion Scouts are young nature enthusiasts dedicated to exploring and protecting the wilds of Azeroth.", description = "Кенарійські розвідники — молоді шанувальники природи, віддані дослідженню та захисту диких земель Азероту.", parent = 0, reputation_index = 57, flags = 0 },
        [2721] = { en = "S03 - Scarlet Crusade", name = "S03 — Багряний Похід", en_description = "Used for Naxxramas NPCs", description = "Використовується для NPC Наксрамаса.", parent = 0, reputation_index = -1, flags = 0 },
        [2723] = { en = "S03 - New Avalon - Scarlet Crusade - Disguise", name = "S03 — Новий Авалон — Багряний Похід — маскування", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2724] = { en = "S03 - New Avalon - Scarlet Crusade - Patrollers", name = "S03 — Новий Авалон — Багряний Похід — патрульні", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2730] = { en = "1.50.0 - Hyjal Attunement - Leyara", name = "1.50.0 — налаштування на Гіджал — Леяра", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2731] = { en = "1.50.0 - Hyjal Attunement - Gol'gere", name = "1.50.0 — налаштування на Гіджал — Ґол'ґере", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2740] = { en = "Kirin Tor", name = "Кірін-Тор", en_description = "An elite cadre of the most powerful wizards in the world and the ruling conclave of magi that leads the magical nation of Dalaran.", description = "Елітний осередок наймогутніших чарівників світу та правлячий конклав магів, що очолює магічну державу Даларан.", parent = 0, reputation_index = 58, flags = 0 },
        [2741] = { en = "Kirin Tor - Broken", name = "Кірін-Тор — зломлені", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2745] = { en = "Timbermaw Hold - Unbound Spirit - Enemies", name = "Оплот Деревопащих — Неприборканий дух — вороги", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 96 },
        [2746] = { en = "Timbermaw Hold - Unbound Spirit - Allies", name = "Оплот Деревопащих — Неприборканий дух — союзники", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 96 },
        [2747] = { en = "Barkskin Burrow", name = "Нора Корошкурих", en_description = "The Barkskin are among the few furbolg tribes untouched by corruption, and dedicate themselves to safeguarding their spiritual heritage to bring harmony back to Hyjal.", description = "Корошкурі — одне з небагатьох племен фурболґів, яких не торкнулося осквернення. Вони присвятили себе збереженню духовної спадщини й прагнуть повернути гармонію Гіджалу.", parent = 0, reputation_index = 59, flags = 0 },
        [2748] = { en = "Shen'dorei", name = "шен'дорай", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2749] = { en = "Al'Aketh", name = "Ал'Акет", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2753] = { en = "Deadwood Furbolg", name = "Фурболґи Мертвого Лісу", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2754] = { en = "CTF - Flag - Neutral", name = "CTF — прапор — нейтральний", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2756] = { en = "Hyjal Skunk", name = "Гіджальський скунс", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2757] = { en = "Zephras Peacekeepers", name = "Миротворці Зефраса", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2758] = { en = "Nightclaw Druids", name = "Друїди Нічного Кігтя", en_description = "The secretive druids of the Shadowgale Forest. They operate independently, apart from any other faction on Zephras Isle.", description = "Потаємні друїди Лісу Тіньового Вітру. Вони діють незалежно від будь-яких інших фракцій острова Зефрас.", parent = 0, reputation_index = 61, flags = 0 },
        [2759] = { en = "Neutral Can Attack", name = "Нейтральний, можна атакувати", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2760] = { en = "Neutral Both But Horde Can Attack", name = "Нейтральний для обох, але Орда може атакувати", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2761] = { en = "Fenwick", name = "Фенвік", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2765] = { en = "Guardians of Hyjal", name = "Вартові Гіджалу", en_description = "Charged with the protection and preservation of Mount Hyjal, this splinter faction of the Cenarion Circle welcomes any who are willing to push back the forces of evil.", description = "Це відгалуження Кенарієвого Кола покликане захищати й зберігати гору Гіджал і радо приймає всіх, хто готовий відтісняти сили зла.", parent = 0, reputation_index = 62, flags = 0 },
        [2768] = { en = "The Blackthorne Pact", name = "Пакт Чорноколючки", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2769] = { en = "Gelkis Outcasts", name = "Вигнанці Ґелкіс", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2777] = { en = "Beast - Predatory Stag", name = "Звір — хижий олень", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2778] = { en = "Windshapers", name = "Формувачі Вітру", en_description = "The Windshapers are shamanistic spiritual leaders of the Skyborne people on Zephras Isle. They honor the elements and seek to gain a better understanding of the nature of the elemental plane to protect the shen'dorei way of life within Skywall.", description = "Формувачі Вітру — шаманські духовні провідники небонародженого народу острова Зефрас. Вони шанують стихії та прагнуть краще зрозуміти природу стихійного плану, щоб захистити спосіб життя шен'дорай у Небесній Стіні.", parent = 0, reputation_index = 70, flags = 0 },
        [2779] = { en = "High Order", name = "Високий Орден", en_description = "The High Order are the Skyborne descendants of the Highborne magisters of Eldre'Thalas. Having spent the past 10,000 years in the realm of Skywall, members of the High Order seek to reclaim the ancient arcane knowledge of their forebears.", description = "Високий Орден — небонароджені нащадки магістрів Високородних з Елдре'Таласа. Провівши останні 10 000 років у царстві Небесної Стіни, його члени прагнуть повернути стародавні арканічні знання своїх предків.", parent = 0, reputation_index = 75, flags = 0 },
        [2782] = { en = "Bolder'ok Clan", name = "Клан Болдер'ок", en_description = "Exiled for betraying their false prophets, these former members of the Twilight's Hammer seek to forge their own path.", description = "Вигнані за зраду своїх лжепророків, ці колишні члени Молота Сутінків прагнуть прокласти власний шлях.", parent = 0, reputation_index = 63, flags = 0 },
        [2785] = { en = "Cenarion Circle (Legendary Event)", name = "Кенарієве Коло (легендарна подія)", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2786] = { en = "Replace", name = "Замінити", en_description = "The Barkskin are among the few furbolg tribes untouched by corruption, and dedicate themselves to safeguarding their spiritual heritage to bring harmony back to Hyjal.", description = "Корошкурі — одне з небагатьох племен фурболґів, яких не торкнулося осквернення. Вони присвятили себе збереженню духовної спадщини й прагнуть повернути гармонію Гіджалу.", parent = 0, reputation_index = -1, flags = 0 },
        [2787] = { en = "Earthen Ring", name = "Коло Землі", en_description = "The Earthen Ring is a loose collective of Horde-aligned shamans and druids who seek to maintain and nurture the balance of nature on Azeroth.", description = "Коло Землі — вільне об'єднання шаманів і друїдів, пов'язаних з Ордою, які прагнуть підтримувати й плекати природну рівновагу Азероту.", parent = 0, reputation_index = 65, flags = 0 },
        [2788] = { en = "Ashen Reign", name = "Попелясте Панування", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2789] = { en = "Ashen Reign - Warlock Disguise", name = "Попелясте Панування — маскування чорнокнижника", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2790] = { en = "CTF - Flag - Neutral", name = "CTF — прапор — нейтральний", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2794] = { en = "PLAYER, Windshaper Skyborne", name = "ГРАВЕЦЬ, небонароджений Формувач Вітру", en_description = "", description = "", parent = 67, reputation_index = -1, flags = 0 },
        [2795] = { en = "PLAYER, High Order Skyborne", name = "ГРАВЕЦЬ, небонароджений Високого Ордену", en_description = "", description = "", parent = 469, reputation_index = -1, flags = 0 },
        [2797] = { en = "OLD", name = "СТАРЕ", en_description = "Elite members of night elf society.", description = "Елітні представники суспільства нічних ельфів.", parent = 0, reputation_index = -1, flags = 0 },
        [2798] = { en = "Darkspear Raiders", name = "Рейдери Темного Списа", en_description = "Loyal to the troll nation, the Darkspear Raiders battle the Theramore Expeditionary Force for control of their ancestral Darkspear Islands.", description = "Вірні трольському народу, Рейдери Темного Списа воюють з Експедиційним корпусом Терамора за контроль над своїми споконвічними Островами Темного Списа.", parent = 892, reputation_index = 67, flags = 0 },
        [2799] = { en = "Theramore Expeditionary Force", name = "Експедиційний корпус Терамора", en_description = "Loyal partisans for their city, the Theramore Expeditionary Force battles the Darkspear Raiders for control of the so-called Darkspear Islands.", description = "Віддані своєму місту бійці Експедиційного корпусу Терамора воюють з Рейдерами Темного Списа за контроль над так званими Островами Темного Списа.", parent = 891, reputation_index = 68, flags = 0 },
        [2800] = { en = "PvP Rank Points", name = "Очки PvP-рангу", en_description = "", description = "", parent = 0, reputation_index = 69, flags = 74 },
        [2801] = { en = "Neutral Both But Alliance Can Attack", name = "Нейтральний для обох, але Альянс може атакувати", en_description = "", description = "", parent = 0, reputation_index = 74, flags = 104 },
        [2802] = { en = "Legacy Track", name = "Шлях спадщини", en_description = "", description = "", parent = 0, reputation_index = 64, flags = 78 },
        [2807] = { en = "DNT Test Reputation", name = "DNT — тестова репутація", en_description = "Will it break? Let's find out!", description = "Зламається? Зараз дізнаємося!", parent = 0, reputation_index = 66, flags = 0 },
        [2813] = { en = "Syndicate Disguise", name = "Маскування під Синдикат", en_description = "", description = "", parent = 0, reputation_index = -1, flags = 0 },
        [2819] = { en = "The Watchers", name = "Вартові", en_description = "An order of powerful jailers and marshals of night elf society. They stand vigilant to ensure that no threat can ever escape their extensive underground network of prisons.", description = "Орден могутніх тюремників і вартових суспільства нічних ельфів. Вони невсипно стежать, щоб жодна загроза не втекла з їхньої розгалуженої мережі підземних в'язниць.", parent = 0, reputation_index = 71, flags = 0 },
        [2826] = { en = "Brotherhood of the Horse", name = "Братство Коня", en_description = "Outcast members of Stormwind's cavalry, these former riders started anew in the unexplored lands along the eastern coast, establishing their home, new relationships, and trade routes.", description = "Вигнанці зі штормовійської кінноти, ці колишні вершники почали нове життя в недосліджених землях східного узбережжя, заснувавши там домівку, нові зв'язки та торговельні шляхи.", parent = 0, reputation_index = 72, flags = 0 },
        [2827] = { en = "Powderfuse", name = "Пороховий Ґніт", en_description = "A strong arm of the Steamwheedle Cartel, this port is home to seafaring sailors and back-alley dealers spanning the eastern sea trading routes.", description = "Сильна опора Картелю Паровиманів: цей порт став домом для мореплавців і торговців із темних провулків, що працюють на торговельних шляхах Східного моря.", parent = 169, reputation_index = 73, flags = 0 },
    },
}

addon_table.client_factions_uk = database

-- Register this same database with the shared display lookup. The supplied
-- wording takes precedence over older generic UI and legacy dictionaries.
local display = {}
for _, row in pairs(database.rows) do
    display[row.en] = row.name
    if row.en_description ~= "" and row.description ~= "" then
        display[row.en_description] = row.description
    end
end
if addon_table.forever_catalog then
    addon_table.forever_catalog.register_ui_source("factions", "curated", display, 1000)
end
