-- Generated by automation/export_client_item_metadata_lua.py; do not edit manually.
-- Client build: 1.60.1.70058; sources: GemProperties.db2
local _, addon_table = ...

local database = {
    sourceBuild = "1.60.1.70058",
    available = true,
    count = 0,
    rows = {
    },
}

addon_table.client_gem_properties = database
return database
