-- Generated by automation/export_client_item_metadata_lua.py; do not edit manually.
-- Client build: 1.60.1.70205; sources: ItemRandomProperties.db2
local _, addon_table = ...

local database = {
    sourceBuild = "1.60.1.70205",
    available = false,
    count = 0,
    rows = {
    },
}

addon_table.client_item_random_properties = database
return database
