-- Generated by automation/export_client_spell_lua.py; do not edit manually.
-- Client build: 1.60.1.70170; sources: TraitDefinition.db2
local _, addon_table = ...

local database = {
    sourceBuild = "1.60.1.70170",
    count = 1,
    rows = {
        [134246] = { name = "16972" },
    },
}

addon_table.client_trait_definition_overrides_en = database
return database
